// Auto-generated stories for vikunja
// Generated by openapi_to_sbt. Do not edit by hand; regenerate instead.
//@provengo summon rest

function resolveDependencies(deps, pkMap) {
  let captured = {};
  while (Object.keys(deps).length > 0) {
    let missingEventSets = Object.values(deps);
    let e = sync({waitFor: missingEventSets});
    for (let k in deps) {
      if (deps[k].contains(e)) {
        let val = (e.data && e.data[k]);
        if (!val && pkMap && pkMap[k]) {
            let mappedKey = pkMap[k];
            val = (e.data && e.data[mappedKey]);
        }
        if (!val && e.data) {
          for (let f in e.data) { if (f.toLowerCase().indexOf("id") > -1) { val = e.data[f]; break; } }
        }
        if (val !== undefined) {
            captured[k] = val;
            delete deps[k];
        }
      }
    }
  }
  return captured;
}


// MULTI-RESOURCE VERIFIED OBLIGATIONS -- generated from OpenAPI
function __mrNamed(n) { return EventSet("wait:"+n, function(e) { return e.name === n; }); }
function __mrPrefix(p) { return EventSet("block:"+p, function(e) { return e.name.indexOf(p) === 0; }); }
function __mrVerifyTaskAbsent(taskId) {
  bp.log.info("Verify deleted task is absent " + taskId);
  svc.get("/tasks/" + taskId, { expectedResponseCodes: [404] });
}
bthread("constraint:task-cleanup", function(){ sync({waitFor:__mrNamed("Milestone:AuxComplete"),block:__mrPrefix("Intent:DeleteTask:")}); });
bthread("constraint:project-cleanup", function(){ sync({waitFor:__mrNamed("Milestone:TasksDeleted"),block:__mrNamed("Intent:DeleteProject")}); });
bthread("crud:project", function(){
  sync({request:Event("Intent:CreateProject")});
  let __mrProject_title = "title_70719";
  let r=projectsCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __mrProject_title);
  let __projectId=r.data["id"];
  sync({request:Event("State:ProjectReady",{id:__projectId})});
  projectsRead(undefined, undefined, undefined, undefined, __projectId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  sync({waitFor:__mrNamed("Milestone:TasksDeleted")});
  sync({request:Event("Intent:DeleteProject")});
  projectsDelete(undefined, undefined, undefined, undefined, __projectId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  sync({request:Event("State:ProjectDeleted")});
});

bthread("scheduler:task-create", function() {
  sync({ waitFor: __mrNamed("State:ProjectReady") });
  let remaining = {};
  remaining["Permit:CreateTask:0"] = Event("Permit:CreateTask:0");
  remaining["Permit:CreateTask:1"] = Event("Permit:CreateTask:1");
  remaining["Permit:CreateTask:2"] = Event("Permit:CreateTask:2");
  remaining["Permit:CreateTask:3"] = Event("Permit:CreateTask:3");
  remaining["Permit:CreateTask:4"] = Event("Permit:CreateTask:4");
  remaining["Permit:CreateTask:5"] = Event("Permit:CreateTask:5");
  while (Object.keys(remaining).length > 0) {
    let selected = sync({ request: Object.values(remaining) });
    delete remaining[selected.name];
  }
});

bthread("scheduler:label-create", function() {
  sync({ waitFor: __mrNamed("State:ProjectReady") });
  let remaining = {};
  remaining["Permit:CreateLabel:0"] = Event("Permit:CreateLabel:0");
  remaining["Permit:CreateLabel:1"] = Event("Permit:CreateLabel:1");
  remaining["Permit:CreateLabel:2"] = Event("Permit:CreateLabel:2");
  while (Object.keys(remaining).length > 0) {
    let selected = sync({ request: Object.values(remaining) });
    delete remaining[selected.name];
  }
});

bthread("crud:task:0", function(){
  let project=sync({waitFor:__mrNamed("State:ProjectReady")}).data;
  sync({waitFor:__mrNamed("Permit:CreateTask:0")});
  let __mrTask0_title = "title_23822";
  sync({request:Event("Intent:CreateTask:0")});
  let r=tasksCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, project.id, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __mrTask0_title);
  let taskId=r.data["task"];
  sync({request:Event("State:TaskReady:0",{id:taskId,title:__mrTask0_title})});
  sync({request:Event("Obligation:VerifyTaskCreate:0",{id:taskId,title:__mrTask0_title})});
  sync({waitFor:__mrNamed("VerifierClosed:TaskCreate:0")});
  sync({waitFor:__mrNamed("Milestone:AuxComplete")});
  sync({request:Event("Intent:UpdateTask:0")});
  tasksUpdate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, __mrTask0_title);
  sync({request:Event("Obligation:VerifyTaskUpdate:0",{id:taskId,title:__mrTask0_title,done:true})});
  sync({waitFor:__mrNamed("VerifierClosed:TaskUpdate:0")});
  sync({waitFor:__mrNamed("Milestone:UpdatesObserved")});
  sync({request:Event("Intent:DeleteTask:0")});
  tasksDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  sync({request:Event("Obligation:VerifyTaskDelete:0",{id:taskId})});
  sync({waitFor:__mrNamed("VerifierClosed:TaskDelete:0")});
});

bthread("verifier:task-create:0", function(){
  let obligation=sync({waitFor:__mrNamed("Obligation:VerifyTaskCreate:0")});
  sync({request:Event("Intent:VerifyTaskCreate:0")});
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, obligation.data.id, undefined);
  sync({request:Event("VerifierClosed:TaskCreate:0",obligation.data)});
});

bthread("verifier:task-update:0", function(){
  let obligation=sync({waitFor:__mrNamed("Obligation:VerifyTaskUpdate:0")});
  sync({request:Event("Intent:VerifyTaskUpdate:0")});
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, obligation.data.id, undefined);
  sync({request:Event("VerifierClosed:TaskUpdate:0",obligation.data)});
  sync({request:Event("State:TaskUpdated:0",obligation.data)});
});

bthread("verifier:task-delete:0", function(){
  let obligation=sync({waitFor:__mrNamed("Obligation:VerifyTaskDelete:0")});
  sync({request:Event("Intent:VerifyTaskDelete:0")});
  __mrVerifyTaskAbsent(obligation.data.id);
  sync({request:Event("State:TaskDeleted:0",obligation.data)});
  sync({request:Event("VerifierClosed:TaskDelete:0",obligation.data)});
});

bthread("constraint:task-create-verifier:0", function(){
  sync({waitFor:__mrNamed("VerifierClosed:TaskCreate:0"),block:__mrNamed("Intent:UpdateTask:0")});
});

bthread("constraint:task-update-verifier:0", function(){
  sync({waitFor:__mrNamed("VerifierClosed:TaskUpdate:0"),block:__mrNamed("Intent:DeleteTask:0")});
});

bthread("crud:task:1", function(){
  let project=sync({waitFor:__mrNamed("State:ProjectReady")}).data;
  sync({waitFor:__mrNamed("Permit:CreateTask:1")});
  let __mrTask1_title = "title_37955";
  sync({request:Event("Intent:CreateTask:1")});
  let r=tasksCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, project.id, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __mrTask1_title);
  let taskId=r.data["task"];
  sync({request:Event("State:TaskReady:1",{id:taskId,title:__mrTask1_title})});
  sync({request:Event("Obligation:VerifyTaskCreate:1",{id:taskId,title:__mrTask1_title})});
  sync({waitFor:__mrNamed("VerifierClosed:TaskCreate:1")});
  sync({waitFor:__mrNamed("Milestone:AuxComplete")});
  sync({request:Event("Intent:UpdateTask:1")});
  tasksUpdate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, __mrTask1_title);
  sync({request:Event("Obligation:VerifyTaskUpdate:1",{id:taskId,title:__mrTask1_title,done:true})});
  sync({waitFor:__mrNamed("VerifierClosed:TaskUpdate:1")});
  sync({waitFor:__mrNamed("Milestone:UpdatesObserved")});
  sync({request:Event("Intent:DeleteTask:1")});
  tasksDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  sync({request:Event("Obligation:VerifyTaskDelete:1",{id:taskId})});
  sync({waitFor:__mrNamed("VerifierClosed:TaskDelete:1")});
});

bthread("verifier:task-create:1", function(){
  let obligation=sync({waitFor:__mrNamed("Obligation:VerifyTaskCreate:1")});
  sync({request:Event("Intent:VerifyTaskCreate:1")});
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, obligation.data.id, undefined);
  sync({request:Event("VerifierClosed:TaskCreate:1",obligation.data)});
});

bthread("verifier:task-update:1", function(){
  let obligation=sync({waitFor:__mrNamed("Obligation:VerifyTaskUpdate:1")});
  sync({request:Event("Intent:VerifyTaskUpdate:1")});
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, obligation.data.id, undefined);
  sync({request:Event("VerifierClosed:TaskUpdate:1",obligation.data)});
  sync({request:Event("State:TaskUpdated:1",obligation.data)});
});

bthread("verifier:task-delete:1", function(){
  let obligation=sync({waitFor:__mrNamed("Obligation:VerifyTaskDelete:1")});
  sync({request:Event("Intent:VerifyTaskDelete:1")});
  __mrVerifyTaskAbsent(obligation.data.id);
  sync({request:Event("State:TaskDeleted:1",obligation.data)});
  sync({request:Event("VerifierClosed:TaskDelete:1",obligation.data)});
});

bthread("constraint:task-create-verifier:1", function(){
  sync({waitFor:__mrNamed("VerifierClosed:TaskCreate:1"),block:__mrNamed("Intent:UpdateTask:1")});
});

bthread("constraint:task-update-verifier:1", function(){
  sync({waitFor:__mrNamed("VerifierClosed:TaskUpdate:1"),block:__mrNamed("Intent:DeleteTask:1")});
});

bthread("crud:task:2", function(){
  let project=sync({waitFor:__mrNamed("State:ProjectReady")}).data;
  sync({waitFor:__mrNamed("Permit:CreateTask:2")});
  let __mrTask2_title = "title_94421";
  sync({request:Event("Intent:CreateTask:2")});
  let r=tasksCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, project.id, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __mrTask2_title);
  let taskId=r.data["task"];
  sync({request:Event("State:TaskReady:2",{id:taskId,title:__mrTask2_title})});
  sync({request:Event("Obligation:VerifyTaskCreate:2",{id:taskId,title:__mrTask2_title})});
  sync({waitFor:__mrNamed("VerifierClosed:TaskCreate:2")});
  sync({waitFor:__mrNamed("Milestone:AuxComplete")});
  sync({request:Event("Intent:UpdateTask:2")});
  tasksUpdate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, __mrTask2_title);
  sync({request:Event("Obligation:VerifyTaskUpdate:2",{id:taskId,title:__mrTask2_title,done:true})});
  sync({waitFor:__mrNamed("VerifierClosed:TaskUpdate:2")});
  sync({waitFor:__mrNamed("Milestone:UpdatesObserved")});
  sync({request:Event("Intent:DeleteTask:2")});
  tasksDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  sync({request:Event("Obligation:VerifyTaskDelete:2",{id:taskId})});
  sync({waitFor:__mrNamed("VerifierClosed:TaskDelete:2")});
});

bthread("verifier:task-create:2", function(){
  let obligation=sync({waitFor:__mrNamed("Obligation:VerifyTaskCreate:2")});
  sync({request:Event("Intent:VerifyTaskCreate:2")});
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, obligation.data.id, undefined);
  sync({request:Event("VerifierClosed:TaskCreate:2",obligation.data)});
});

bthread("verifier:task-update:2", function(){
  let obligation=sync({waitFor:__mrNamed("Obligation:VerifyTaskUpdate:2")});
  sync({request:Event("Intent:VerifyTaskUpdate:2")});
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, obligation.data.id, undefined);
  sync({request:Event("VerifierClosed:TaskUpdate:2",obligation.data)});
  sync({request:Event("State:TaskUpdated:2",obligation.data)});
});

bthread("verifier:task-delete:2", function(){
  let obligation=sync({waitFor:__mrNamed("Obligation:VerifyTaskDelete:2")});
  sync({request:Event("Intent:VerifyTaskDelete:2")});
  __mrVerifyTaskAbsent(obligation.data.id);
  sync({request:Event("State:TaskDeleted:2",obligation.data)});
  sync({request:Event("VerifierClosed:TaskDelete:2",obligation.data)});
});

bthread("constraint:task-create-verifier:2", function(){
  sync({waitFor:__mrNamed("VerifierClosed:TaskCreate:2"),block:__mrNamed("Intent:UpdateTask:2")});
});

bthread("constraint:task-update-verifier:2", function(){
  sync({waitFor:__mrNamed("VerifierClosed:TaskUpdate:2"),block:__mrNamed("Intent:DeleteTask:2")});
});

bthread("crud:task:3", function(){
  let project=sync({waitFor:__mrNamed("State:ProjectReady")}).data;
  sync({waitFor:__mrNamed("Permit:CreateTask:3")});
  let __mrTask3_title = "title_60204";
  sync({request:Event("Intent:CreateTask:3")});
  let r=tasksCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, project.id, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __mrTask3_title);
  let taskId=r.data["task"];
  sync({request:Event("State:TaskReady:3",{id:taskId,title:__mrTask3_title})});
  sync({request:Event("Obligation:VerifyTaskCreate:3",{id:taskId,title:__mrTask3_title})});
  sync({waitFor:__mrNamed("VerifierClosed:TaskCreate:3")});
  sync({waitFor:__mrNamed("Milestone:AuxComplete")});
  sync({request:Event("Intent:UpdateTask:3")});
  tasksUpdate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, __mrTask3_title);
  sync({request:Event("Obligation:VerifyTaskUpdate:3",{id:taskId,title:__mrTask3_title,done:true})});
  sync({waitFor:__mrNamed("VerifierClosed:TaskUpdate:3")});
  sync({waitFor:__mrNamed("Milestone:UpdatesObserved")});
  sync({request:Event("Intent:DeleteTask:3")});
  tasksDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  sync({request:Event("Obligation:VerifyTaskDelete:3",{id:taskId})});
  sync({waitFor:__mrNamed("VerifierClosed:TaskDelete:3")});
});

bthread("verifier:task-create:3", function(){
  let obligation=sync({waitFor:__mrNamed("Obligation:VerifyTaskCreate:3")});
  sync({request:Event("Intent:VerifyTaskCreate:3")});
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, obligation.data.id, undefined);
  sync({request:Event("VerifierClosed:TaskCreate:3",obligation.data)});
});

bthread("verifier:task-update:3", function(){
  let obligation=sync({waitFor:__mrNamed("Obligation:VerifyTaskUpdate:3")});
  sync({request:Event("Intent:VerifyTaskUpdate:3")});
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, obligation.data.id, undefined);
  sync({request:Event("VerifierClosed:TaskUpdate:3",obligation.data)});
  sync({request:Event("State:TaskUpdated:3",obligation.data)});
});

bthread("verifier:task-delete:3", function(){
  let obligation=sync({waitFor:__mrNamed("Obligation:VerifyTaskDelete:3")});
  sync({request:Event("Intent:VerifyTaskDelete:3")});
  __mrVerifyTaskAbsent(obligation.data.id);
  sync({request:Event("State:TaskDeleted:3",obligation.data)});
  sync({request:Event("VerifierClosed:TaskDelete:3",obligation.data)});
});

bthread("constraint:task-create-verifier:3", function(){
  sync({waitFor:__mrNamed("VerifierClosed:TaskCreate:3"),block:__mrNamed("Intent:UpdateTask:3")});
});

bthread("constraint:task-update-verifier:3", function(){
  sync({waitFor:__mrNamed("VerifierClosed:TaskUpdate:3"),block:__mrNamed("Intent:DeleteTask:3")});
});

bthread("crud:task:4", function(){
  let project=sync({waitFor:__mrNamed("State:ProjectReady")}).data;
  sync({waitFor:__mrNamed("Permit:CreateTask:4")});
  let __mrTask4_title = "title_19967";
  sync({request:Event("Intent:CreateTask:4")});
  let r=tasksCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, project.id, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __mrTask4_title);
  let taskId=r.data["task"];
  sync({request:Event("State:TaskReady:4",{id:taskId,title:__mrTask4_title})});
  sync({request:Event("Obligation:VerifyTaskCreate:4",{id:taskId,title:__mrTask4_title})});
  sync({waitFor:__mrNamed("VerifierClosed:TaskCreate:4")});
  sync({waitFor:__mrNamed("Milestone:AuxComplete")});
  sync({request:Event("Intent:UpdateTask:4")});
  tasksUpdate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, __mrTask4_title);
  sync({request:Event("Obligation:VerifyTaskUpdate:4",{id:taskId,title:__mrTask4_title,done:true})});
  sync({waitFor:__mrNamed("VerifierClosed:TaskUpdate:4")});
  sync({waitFor:__mrNamed("Milestone:UpdatesObserved")});
  sync({request:Event("Intent:DeleteTask:4")});
  tasksDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  sync({request:Event("Obligation:VerifyTaskDelete:4",{id:taskId})});
  sync({waitFor:__mrNamed("VerifierClosed:TaskDelete:4")});
});

bthread("verifier:task-create:4", function(){
  let obligation=sync({waitFor:__mrNamed("Obligation:VerifyTaskCreate:4")});
  sync({request:Event("Intent:VerifyTaskCreate:4")});
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, obligation.data.id, undefined);
  sync({request:Event("VerifierClosed:TaskCreate:4",obligation.data)});
});

bthread("verifier:task-update:4", function(){
  let obligation=sync({waitFor:__mrNamed("Obligation:VerifyTaskUpdate:4")});
  sync({request:Event("Intent:VerifyTaskUpdate:4")});
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, obligation.data.id, undefined);
  sync({request:Event("VerifierClosed:TaskUpdate:4",obligation.data)});
  sync({request:Event("State:TaskUpdated:4",obligation.data)});
});

bthread("verifier:task-delete:4", function(){
  let obligation=sync({waitFor:__mrNamed("Obligation:VerifyTaskDelete:4")});
  sync({request:Event("Intent:VerifyTaskDelete:4")});
  __mrVerifyTaskAbsent(obligation.data.id);
  sync({request:Event("State:TaskDeleted:4",obligation.data)});
  sync({request:Event("VerifierClosed:TaskDelete:4",obligation.data)});
});

bthread("constraint:task-create-verifier:4", function(){
  sync({waitFor:__mrNamed("VerifierClosed:TaskCreate:4"),block:__mrNamed("Intent:UpdateTask:4")});
});

bthread("constraint:task-update-verifier:4", function(){
  sync({waitFor:__mrNamed("VerifierClosed:TaskUpdate:4"),block:__mrNamed("Intent:DeleteTask:4")});
});

bthread("crud:task:5", function(){
  let project=sync({waitFor:__mrNamed("State:ProjectReady")}).data;
  sync({waitFor:__mrNamed("Permit:CreateTask:5")});
  let __mrTask5_title = "title_8683";
  sync({request:Event("Intent:CreateTask:5")});
  let r=tasksCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, project.id, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __mrTask5_title);
  let taskId=r.data["task"];
  sync({request:Event("State:TaskReady:5",{id:taskId,title:__mrTask5_title})});
  sync({request:Event("Obligation:VerifyTaskCreate:5",{id:taskId,title:__mrTask5_title})});
  sync({waitFor:__mrNamed("VerifierClosed:TaskCreate:5")});
  sync({waitFor:__mrNamed("Milestone:AuxComplete")});
  sync({request:Event("Intent:UpdateTask:5")});
  tasksUpdate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, __mrTask5_title);
  sync({request:Event("Obligation:VerifyTaskUpdate:5",{id:taskId,title:__mrTask5_title,done:true})});
  sync({waitFor:__mrNamed("VerifierClosed:TaskUpdate:5")});
  sync({waitFor:__mrNamed("Milestone:UpdatesObserved")});
  sync({request:Event("Intent:DeleteTask:5")});
  tasksDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  sync({request:Event("Obligation:VerifyTaskDelete:5",{id:taskId})});
  sync({waitFor:__mrNamed("VerifierClosed:TaskDelete:5")});
});

bthread("verifier:task-create:5", function(){
  let obligation=sync({waitFor:__mrNamed("Obligation:VerifyTaskCreate:5")});
  sync({request:Event("Intent:VerifyTaskCreate:5")});
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, obligation.data.id, undefined);
  sync({request:Event("VerifierClosed:TaskCreate:5",obligation.data)});
});

bthread("verifier:task-update:5", function(){
  let obligation=sync({waitFor:__mrNamed("Obligation:VerifyTaskUpdate:5")});
  sync({request:Event("Intent:VerifyTaskUpdate:5")});
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, obligation.data.id, undefined);
  sync({request:Event("VerifierClosed:TaskUpdate:5",obligation.data)});
  sync({request:Event("State:TaskUpdated:5",obligation.data)});
});

bthread("verifier:task-delete:5", function(){
  let obligation=sync({waitFor:__mrNamed("Obligation:VerifyTaskDelete:5")});
  sync({request:Event("Intent:VerifyTaskDelete:5")});
  __mrVerifyTaskAbsent(obligation.data.id);
  sync({request:Event("State:TaskDeleted:5",obligation.data)});
  sync({request:Event("VerifierClosed:TaskDelete:5",obligation.data)});
});

bthread("constraint:task-create-verifier:5", function(){
  sync({waitFor:__mrNamed("VerifierClosed:TaskCreate:5"),block:__mrNamed("Intent:UpdateTask:5")});
});

bthread("constraint:task-update-verifier:5", function(){
  sync({waitFor:__mrNamed("VerifierClosed:TaskUpdate:5"),block:__mrNamed("Intent:DeleteTask:5")});
});

bthread("crud:label:0",function(){
  sync({waitFor:__mrNamed("Permit:CreateLabel:0")});
  let __mrLabel0_title = "title_10983";
  let r=labelsCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __mrLabel0_title);
  let labelId=r.data["id"];
  sync({request:Event("State:LabelReady:0",{id:labelId})});
  labelsRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, labelId, undefined, undefined, undefined, undefined);
  sync({waitFor:__mrNamed("Milestone:LabelsDetached")});
  labelsDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, labelId, undefined, undefined, undefined, undefined);
  sync({request:Event("State:LabelDeleted:0",{id:labelId})});
});

bthread("crud:label:1",function(){
  sync({waitFor:__mrNamed("Permit:CreateLabel:1")});
  let __mrLabel1_title = "title_98174";
  let r=labelsCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __mrLabel1_title);
  let labelId=r.data["id"];
  sync({request:Event("State:LabelReady:1",{id:labelId})});
  labelsRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, labelId, undefined, undefined, undefined, undefined);
  sync({waitFor:__mrNamed("Milestone:LabelsDetached")});
  labelsDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, labelId, undefined, undefined, undefined, undefined);
  sync({request:Event("State:LabelDeleted:1",{id:labelId})});
});

bthread("crud:label:2",function(){
  sync({waitFor:__mrNamed("Permit:CreateLabel:2")});
  let __mrLabel2_title = "title_83533";
  let r=labelsCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __mrLabel2_title);
  let labelId=r.data["id"];
  sync({request:Event("State:LabelReady:2",{id:labelId})});
  labelsRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, labelId, undefined, undefined, undefined, undefined);
  sync({waitFor:__mrNamed("Milestone:LabelsDetached")});
  labelsDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, labelId, undefined, undefined, undefined, undefined);
  sync({request:Event("State:LabelDeleted:2",{id:labelId})});
});

bthread("association:label:0",function(){
  let p={task:__mrNamed("State:TaskReady:0"),label:__mrNamed("State:LabelReady:0")}; let taskId,labelId;
  while(Object.keys(p).length){let e=sync({waitFor:Object.values(p)});if(p.task&&p.task.contains(e)){taskId=e.data.id;delete p.task;}else if(p.label&&p.label.contains(e)){labelId=e.data.id;delete p.label;}}
  taskLabelsCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, labelId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  taskLabelsList(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  sync({request:Event("State:LabelAttached:0")});
  sync({waitFor:__mrNamed("Milestone:AuxReadyForMutation")});
  taskLabelsDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, labelId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  taskLabelsList(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  sync({request:Event("State:LabelDetached:0")});
});

bthread("association:label:1",function(){
  let p={task:__mrNamed("State:TaskReady:1"),label:__mrNamed("State:LabelReady:1")}; let taskId,labelId;
  while(Object.keys(p).length){let e=sync({waitFor:Object.values(p)});if(p.task&&p.task.contains(e)){taskId=e.data.id;delete p.task;}else if(p.label&&p.label.contains(e)){labelId=e.data.id;delete p.label;}}
  taskLabelsCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, labelId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  taskLabelsList(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  sync({request:Event("State:LabelAttached:1")});
  sync({waitFor:__mrNamed("Milestone:AuxReadyForMutation")});
  taskLabelsDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, labelId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  taskLabelsList(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  sync({request:Event("State:LabelDetached:1")});
});

bthread("association:label:2",function(){
  let p={task:__mrNamed("State:TaskReady:2"),label:__mrNamed("State:LabelReady:2")}; let taskId,labelId;
  while(Object.keys(p).length){let e=sync({waitFor:Object.values(p)});if(p.task&&p.task.contains(e)){taskId=e.data.id;delete p.task;}else if(p.label&&p.label.contains(e)){labelId=e.data.id;delete p.label;}}
  taskLabelsCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, labelId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  taskLabelsList(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  sync({request:Event("State:LabelAttached:2")});
  sync({waitFor:__mrNamed("Milestone:AuxReadyForMutation")});
  taskLabelsDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, labelId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  taskLabelsList(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  sync({request:Event("State:LabelDetached:2")});
});

bthread("subresource:comment:0",function(){
  let taskId=sync({waitFor:__mrNamed("State:TaskReady:0")}).data.id;
  let initialValue="0_96541";
  let r=taskCommentsCreate(undefined, undefined, undefined, undefined, undefined, undefined, initialValue, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  let commentId=(r.data["id"]!==undefined?r.data["id"]:r.data.__httpResponse["id"]);
  sync({request:Event("State:CommentReady:0",{id:commentId})});
  taskCommentsRead(undefined, undefined, undefined, undefined, undefined, commentId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  taskCommentsList(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  let changedValue="0_64680";
  taskCommentsUpdate(undefined, undefined, undefined, undefined, undefined, undefined, changedValue, commentId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  taskCommentsRead(undefined, undefined, undefined, undefined, undefined, commentId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  sync({request:Event("State:CommentUpdated:0")});
  sync({waitFor:__mrNamed("Milestone:AuxReadyForMutation")});
  taskCommentsDelete(undefined, undefined, undefined, undefined, undefined, commentId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  taskCommentsList(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  sync({request:Event("State:CommentDeleted:0")});
});

bthread("subresource:comment:1",function(){
  let taskId=sync({waitFor:__mrNamed("State:TaskReady:1")}).data.id;
  let initialValue="1_69246";
  let r=taskCommentsCreate(undefined, undefined, undefined, undefined, undefined, undefined, initialValue, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  let commentId=(r.data["id"]!==undefined?r.data["id"]:r.data.__httpResponse["id"]);
  sync({request:Event("State:CommentReady:1",{id:commentId})});
  taskCommentsRead(undefined, undefined, undefined, undefined, undefined, commentId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  taskCommentsList(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  let changedValue="1_83551";
  taskCommentsUpdate(undefined, undefined, undefined, undefined, undefined, undefined, changedValue, commentId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  taskCommentsRead(undefined, undefined, undefined, undefined, undefined, commentId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  sync({request:Event("State:CommentUpdated:1")});
  sync({waitFor:__mrNamed("Milestone:AuxReadyForMutation")});
  taskCommentsDelete(undefined, undefined, undefined, undefined, undefined, commentId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  taskCommentsList(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  sync({request:Event("State:CommentDeleted:1")});
});

bthread("subresource:comment:2",function(){
  let taskId=sync({waitFor:__mrNamed("State:TaskReady:2")}).data.id;
  let initialValue="2_50350";
  let r=taskCommentsCreate(undefined, undefined, undefined, undefined, undefined, undefined, initialValue, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  let commentId=(r.data["id"]!==undefined?r.data["id"]:r.data.__httpResponse["id"]);
  sync({request:Event("State:CommentReady:2",{id:commentId})});
  taskCommentsRead(undefined, undefined, undefined, undefined, undefined, commentId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  taskCommentsList(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  let changedValue="2_45281";
  taskCommentsUpdate(undefined, undefined, undefined, undefined, undefined, undefined, changedValue, commentId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  taskCommentsRead(undefined, undefined, undefined, undefined, undefined, commentId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  sync({request:Event("State:CommentUpdated:2")});
  sync({waitFor:__mrNamed("Milestone:AuxReadyForMutation")});
  taskCommentsDelete(undefined, undefined, undefined, undefined, undefined, commentId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  taskCommentsList(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  sync({request:Event("State:CommentDeleted:2")});
});

bthread("subresource:comment:3",function(){
  let taskId=sync({waitFor:__mrNamed("State:TaskReady:3")}).data.id;
  let initialValue="3_3609";
  let r=taskCommentsCreate(undefined, undefined, undefined, undefined, undefined, undefined, initialValue, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  let commentId=(r.data["id"]!==undefined?r.data["id"]:r.data.__httpResponse["id"]);
  sync({request:Event("State:CommentReady:3",{id:commentId})});
  taskCommentsRead(undefined, undefined, undefined, undefined, undefined, commentId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  taskCommentsList(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  let changedValue="3_93169";
  taskCommentsUpdate(undefined, undefined, undefined, undefined, undefined, undefined, changedValue, commentId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  taskCommentsRead(undefined, undefined, undefined, undefined, undefined, commentId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  sync({request:Event("State:CommentUpdated:3")});
  sync({waitFor:__mrNamed("Milestone:AuxReadyForMutation")});
  taskCommentsDelete(undefined, undefined, undefined, undefined, undefined, commentId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  taskCommentsList(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, taskId, undefined);
  sync({request:Event("State:CommentDeleted:3")});
});

bthread("relation:edge:0",function(){
  let p={a:__mrNamed("State:TaskReady:0"),b:__mrNamed("State:TaskReady:1")};let a,b;
  while(Object.keys(p).length){let e=sync({waitFor:Object.values(p)});if(p.a&&p.a.contains(e)){a=e.data.id;delete p.a;}else if(p.b&&p.b.contains(e)){b=e.data.id;delete p.b;}}
  tasksRelationsCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, b, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "subtask", undefined, undefined, undefined, undefined, undefined, undefined, a, undefined);
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, a, undefined);
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, b, undefined);
  sync({request:Event("State:RelationObserved:0")});
  sync({waitFor:__mrNamed("Milestone:AuxReadyForMutation")});
  tasksRelationsDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, b, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "subtask", undefined, undefined, undefined, undefined, undefined, undefined, a, undefined);
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, a, undefined);
  sync({request:Event("State:RelationDeleted:0")});
});

bthread("relation:edge:1",function(){
  let p={a:__mrNamed("State:TaskReady:1"),b:__mrNamed("State:TaskReady:2")};let a,b;
  while(Object.keys(p).length){let e=sync({waitFor:Object.values(p)});if(p.a&&p.a.contains(e)){a=e.data.id;delete p.a;}else if(p.b&&p.b.contains(e)){b=e.data.id;delete p.b;}}
  tasksRelationsCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, b, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "parenttask", undefined, undefined, undefined, undefined, undefined, undefined, a, undefined);
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, a, undefined);
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, b, undefined);
  sync({request:Event("State:RelationObserved:1")});
  sync({waitFor:__mrNamed("Milestone:AuxReadyForMutation")});
  tasksRelationsDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, b, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "parenttask", undefined, undefined, undefined, undefined, undefined, undefined, a, undefined);
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, a, undefined);
  sync({request:Event("State:RelationDeleted:1")});
});

bthread("relation:edge:2",function(){
  let p={a:__mrNamed("State:TaskReady:2"),b:__mrNamed("State:TaskReady:3")};let a,b;
  while(Object.keys(p).length){let e=sync({waitFor:Object.values(p)});if(p.a&&p.a.contains(e)){a=e.data.id;delete p.a;}else if(p.b&&p.b.contains(e)){b=e.data.id;delete p.b;}}
  tasksRelationsCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, b, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "related", undefined, undefined, undefined, undefined, undefined, undefined, a, undefined);
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, a, undefined);
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, b, undefined);
  sync({request:Event("State:RelationObserved:2")});
  sync({waitFor:__mrNamed("Milestone:AuxReadyForMutation")});
  tasksRelationsDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, b, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "related", undefined, undefined, undefined, undefined, undefined, undefined, a, undefined);
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, a, undefined);
  sync({request:Event("State:RelationDeleted:2")});
});

bthread("relation:edge:3",function(){
  let p={a:__mrNamed("State:TaskReady:3"),b:__mrNamed("State:TaskReady:4")};let a,b;
  while(Object.keys(p).length){let e=sync({waitFor:Object.values(p)});if(p.a&&p.a.contains(e)){a=e.data.id;delete p.a;}else if(p.b&&p.b.contains(e)){b=e.data.id;delete p.b;}}
  tasksRelationsCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, b, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "duplicateof", undefined, undefined, undefined, undefined, undefined, undefined, a, undefined);
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, a, undefined);
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, b, undefined);
  sync({request:Event("State:RelationObserved:3")});
  sync({waitFor:__mrNamed("Milestone:AuxReadyForMutation")});
  tasksRelationsDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, b, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "duplicateof", undefined, undefined, undefined, undefined, undefined, undefined, a, undefined);
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, a, undefined);
  sync({request:Event("State:RelationDeleted:3")});
});

bthread("relation:edge:4",function(){
  let p={a:__mrNamed("State:TaskReady:4"),b:__mrNamed("State:TaskReady:5")};let a,b;
  while(Object.keys(p).length){let e=sync({waitFor:Object.values(p)});if(p.a&&p.a.contains(e)){a=e.data.id;delete p.a;}else if(p.b&&p.b.contains(e)){b=e.data.id;delete p.b;}}
  tasksRelationsCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, b, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "duplicates", undefined, undefined, undefined, undefined, undefined, undefined, a, undefined);
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, a, undefined);
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, b, undefined);
  sync({request:Event("State:RelationObserved:4")});
  sync({waitFor:__mrNamed("Milestone:AuxReadyForMutation")});
  tasksRelationsDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, b, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "duplicates", undefined, undefined, undefined, undefined, undefined, undefined, a, undefined);
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, a, undefined);
  sync({request:Event("State:RelationDeleted:4")});
});

bthread("coordinator:tasks-ready", function() {
  let pending = {};
  pending["State:TaskReady:0"] = __mrNamed("State:TaskReady:0");
  pending["State:TaskReady:1"] = __mrNamed("State:TaskReady:1");
  pending["State:TaskReady:2"] = __mrNamed("State:TaskReady:2");
  pending["State:TaskReady:3"] = __mrNamed("State:TaskReady:3");
  pending["State:TaskReady:4"] = __mrNamed("State:TaskReady:4");
  pending["State:TaskReady:5"] = __mrNamed("State:TaskReady:5");
  while (Object.keys(pending).length > 0) {
    let seen = sync({ waitFor: Object.values(pending) });
    if (pending[seen.name]) delete pending[seen.name];
  }
  sync({ request: Event("Milestone:TasksReady") });
});

bthread("coordinator:relations-observed", function() {
  let pending = {};
  pending["State:RelationObserved:0"] = __mrNamed("State:RelationObserved:0");
  pending["State:RelationObserved:1"] = __mrNamed("State:RelationObserved:1");
  pending["State:RelationObserved:2"] = __mrNamed("State:RelationObserved:2");
  pending["State:RelationObserved:3"] = __mrNamed("State:RelationObserved:3");
  pending["State:RelationObserved:4"] = __mrNamed("State:RelationObserved:4");
  while (Object.keys(pending).length > 0) {
    let seen = sync({ waitFor: Object.values(pending) });
    if (pending[seen.name]) delete pending[seen.name];
  }
  sync({ request: Event("Milestone:RelationsObserved") });
});

bthread("coordinator:aux-ready-for-mutation", function() {
  let pending = {};
  pending["State:RelationObserved:0"] = __mrNamed("State:RelationObserved:0");
  pending["State:RelationObserved:1"] = __mrNamed("State:RelationObserved:1");
  pending["State:RelationObserved:2"] = __mrNamed("State:RelationObserved:2");
  pending["State:RelationObserved:3"] = __mrNamed("State:RelationObserved:3");
  pending["State:RelationObserved:4"] = __mrNamed("State:RelationObserved:4");
  pending["State:LabelAttached:0"] = __mrNamed("State:LabelAttached:0");
  pending["State:LabelAttached:1"] = __mrNamed("State:LabelAttached:1");
  pending["State:LabelAttached:2"] = __mrNamed("State:LabelAttached:2");
  pending["State:CommentUpdated:0"] = __mrNamed("State:CommentUpdated:0");
  pending["State:CommentUpdated:1"] = __mrNamed("State:CommentUpdated:1");
  pending["State:CommentUpdated:2"] = __mrNamed("State:CommentUpdated:2");
  pending["State:CommentUpdated:3"] = __mrNamed("State:CommentUpdated:3");
  while (Object.keys(pending).length > 0) {
    let seen = sync({ waitFor: Object.values(pending) });
    if (pending[seen.name]) delete pending[seen.name];
  }
  sync({ request: Event("Milestone:AuxReadyForMutation") });
});

bthread("coordinator:aux", function() {
  let pending = {};
  pending["State:LabelDetached:0"] = __mrNamed("State:LabelDetached:0");
  pending["State:LabelDetached:1"] = __mrNamed("State:LabelDetached:1");
  pending["State:LabelDetached:2"] = __mrNamed("State:LabelDetached:2");
  pending["State:CommentDeleted:0"] = __mrNamed("State:CommentDeleted:0");
  pending["State:CommentDeleted:1"] = __mrNamed("State:CommentDeleted:1");
  pending["State:CommentDeleted:2"] = __mrNamed("State:CommentDeleted:2");
  pending["State:CommentDeleted:3"] = __mrNamed("State:CommentDeleted:3");
  pending["State:RelationDeleted:0"] = __mrNamed("State:RelationDeleted:0");
  pending["State:RelationDeleted:1"] = __mrNamed("State:RelationDeleted:1");
  pending["State:RelationDeleted:2"] = __mrNamed("State:RelationDeleted:2");
  pending["State:RelationDeleted:3"] = __mrNamed("State:RelationDeleted:3");
  pending["State:RelationDeleted:4"] = __mrNamed("State:RelationDeleted:4");
  while (Object.keys(pending).length > 0) {
    let seen = sync({ waitFor: Object.values(pending) });
    if (pending[seen.name]) delete pending[seen.name];
  }
  sync({ request: Event("Milestone:AuxComplete") });
});

bthread("coordinator:labels-detached", function() {
  let pending = {};
  pending["State:LabelDetached:0"] = __mrNamed("State:LabelDetached:0");
  pending["State:LabelDetached:1"] = __mrNamed("State:LabelDetached:1");
  pending["State:LabelDetached:2"] = __mrNamed("State:LabelDetached:2");
  while (Object.keys(pending).length > 0) {
    let seen = sync({ waitFor: Object.values(pending) });
    if (pending[seen.name]) delete pending[seen.name];
  }
  sync({ request: Event("Milestone:LabelsDetached") });
});

bthread("coordinator:updates", function() {
  let pending = {};
  pending["State:TaskUpdated:0"] = __mrNamed("State:TaskUpdated:0");
  pending["State:TaskUpdated:1"] = __mrNamed("State:TaskUpdated:1");
  pending["State:TaskUpdated:2"] = __mrNamed("State:TaskUpdated:2");
  pending["State:TaskUpdated:3"] = __mrNamed("State:TaskUpdated:3");
  pending["State:TaskUpdated:4"] = __mrNamed("State:TaskUpdated:4");
  pending["State:TaskUpdated:5"] = __mrNamed("State:TaskUpdated:5");
  while (Object.keys(pending).length > 0) {
    let seen = sync({ waitFor: Object.values(pending) });
    if (pending[seen.name]) delete pending[seen.name];
  }
  sync({ request: Event("Milestone:UpdatesObserved") });
});

bthread("coordinator:tasks-deleted", function() {
  let pending = {};
  pending["State:TaskDeleted:0"] = __mrNamed("State:TaskDeleted:0");
  pending["State:TaskDeleted:1"] = __mrNamed("State:TaskDeleted:1");
  pending["State:TaskDeleted:2"] = __mrNamed("State:TaskDeleted:2");
  pending["State:TaskDeleted:3"] = __mrNamed("State:TaskDeleted:3");
  pending["State:TaskDeleted:4"] = __mrNamed("State:TaskDeleted:4");
  pending["State:TaskDeleted:5"] = __mrNamed("State:TaskDeleted:5");
  while (Object.keys(pending).length > 0) {
    let seen = sync({ waitFor: Object.values(pending) });
    if (pending[seen.name]) delete pending[seen.name];
  }
  sync({ request: Event("Milestone:TasksDeleted") });
});

bthread("coordinator:labels-deleted", function() {
  let pending = {};
  pending["State:LabelDeleted:0"] = __mrNamed("State:LabelDeleted:0");
  pending["State:LabelDeleted:1"] = __mrNamed("State:LabelDeleted:1");
  pending["State:LabelDeleted:2"] = __mrNamed("State:LabelDeleted:2");
  while (Object.keys(pending).length > 0) {
    let seen = sync({ waitFor: Object.values(pending) });
    if (pending[seen.name]) delete pending[seen.name];
  }
  sync({ request: Event("Milestone:LabelsDeleted") });
});

bthread("coordinator:task-verifier-obligations", function() {
  let pending = {};
  pending["VerifierClosed:TaskCreate:0"] = __mrNamed("VerifierClosed:TaskCreate:0");
  pending["VerifierClosed:TaskCreate:1"] = __mrNamed("VerifierClosed:TaskCreate:1");
  pending["VerifierClosed:TaskCreate:2"] = __mrNamed("VerifierClosed:TaskCreate:2");
  pending["VerifierClosed:TaskCreate:3"] = __mrNamed("VerifierClosed:TaskCreate:3");
  pending["VerifierClosed:TaskCreate:4"] = __mrNamed("VerifierClosed:TaskCreate:4");
  pending["VerifierClosed:TaskCreate:5"] = __mrNamed("VerifierClosed:TaskCreate:5");
  pending["VerifierClosed:TaskUpdate:0"] = __mrNamed("VerifierClosed:TaskUpdate:0");
  pending["VerifierClosed:TaskUpdate:1"] = __mrNamed("VerifierClosed:TaskUpdate:1");
  pending["VerifierClosed:TaskUpdate:2"] = __mrNamed("VerifierClosed:TaskUpdate:2");
  pending["VerifierClosed:TaskUpdate:3"] = __mrNamed("VerifierClosed:TaskUpdate:3");
  pending["VerifierClosed:TaskUpdate:4"] = __mrNamed("VerifierClosed:TaskUpdate:4");
  pending["VerifierClosed:TaskUpdate:5"] = __mrNamed("VerifierClosed:TaskUpdate:5");
  pending["VerifierClosed:TaskDelete:0"] = __mrNamed("VerifierClosed:TaskDelete:0");
  pending["VerifierClosed:TaskDelete:1"] = __mrNamed("VerifierClosed:TaskDelete:1");
  pending["VerifierClosed:TaskDelete:2"] = __mrNamed("VerifierClosed:TaskDelete:2");
  pending["VerifierClosed:TaskDelete:3"] = __mrNamed("VerifierClosed:TaskDelete:3");
  pending["VerifierClosed:TaskDelete:4"] = __mrNamed("VerifierClosed:TaskDelete:4");
  pending["VerifierClosed:TaskDelete:5"] = __mrNamed("VerifierClosed:TaskDelete:5");
  while (Object.keys(pending).length > 0) {
    let seen = sync({ waitFor: Object.values(pending) });
    if (pending[seen.name]) delete pending[seen.name];
  }
  sync({ request: Event("Milestone:AllTaskVerifiersClosed") });
});

bthread("coordinator:complete", function() {
  let pending = {};
  pending["State:ProjectDeleted"] = __mrNamed("State:ProjectDeleted");
  pending["Milestone:LabelsDeleted"] = __mrNamed("Milestone:LabelsDeleted");
  pending["Milestone:AllTaskVerifiersClosed"] = __mrNamed("Milestone:AllTaskVerifiersClosed");
  while (Object.keys(pending).length > 0) {
    let seen = sync({ waitFor: Object.values(pending) });
    if (pending[seen.name]) delete pending[seen.name];
  }
  sync({ request: Event("MultiResourceVerifiedObligationsComplete") });
});
