// Auto-generated stories for vikunja
// Generated by openapi_to_sbt. Do not edit by hand; regenerate instead.
//@provengo summon rest

function resolveDependencies(deps, pkMap) {
  let captured = {};
  while (Object.keys(deps).length > 0) {
    let missingEventSets = Object.values(deps);
    let e = sync({waitFor: missingEventSets});
    for (let k in deps) {
      if (deps[k].contains(e)) {
        let val = (e.data && e.data[k]);
        if (!val && pkMap && pkMap[k]) {
            let mappedKey = pkMap[k];
            val = (e.data && e.data[mappedKey]);
        }
        if (!val && e.data) {
          for (let f in e.data) { if (f.toLowerCase().indexOf("id") > -1) { val = e.data[f]; break; } }
        }
        if (val !== undefined) {
            captured[k] = val;
            delete deps[k];
        }
      }
    }
  }
  return captured;
}


// =============================================================================
// INTERLEAVED RELATIONAL LIFECYCLE
// OpenAPI-derived BP stories; no end-to-end sequence is pre-scripted.
// =============================================================================
function __named(name) {
  return EventSet("wait:" + name, function(e) { return e.name === name; });
}
function __intentPrefix(prefix) {
  return EventSet("block:" + prefix, function(e) { return e.name.indexOf(prefix) === 0; });
}

// Explicit BP constraints.  The requesters also wait for the same
// milestones; block makes the prohibition a model-level invariant.
bthread("constraint:block-task-cleanup", function() {
  sync({ waitFor: __named("Milestone:UpdatesObserved"),
         block: __intentPrefix("Intent:DeleteTask:") });
});
bthread("constraint:block-parent-cleanup", function() {
  sync({ waitFor: __named("Milestone:AllTasksDeleted"),
         block: __named("Intent:DeleteParent") });
});

bthread("crud:parent", function() {
  sync({ request: Event("Intent:CreateParent") });
  let __bpParentCreate_title = "title_53885";
  let __parentResult = projectsCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __bpParentCreate_title);
  let __parentId = __parentResult.data["id"];
  sync({ request: Event("State:ParentReady", { id: __parentId }) });
  sync({ request: Event("Intent:ReadParent") });
  projectsRead(undefined, undefined, undefined, undefined, __parentId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  sync({ waitFor: __named("Milestone:AllTasksDeleted") });
  sync({ request: Event("Intent:DeleteParent") });
  projectsDelete(undefined, undefined, undefined, undefined, __parentId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  sync({ request: Event("State:ParentDeleted") });
});

bthread("crud:child:0", function() {
  let __parentReady = sync({ waitFor: __named("State:ParentReady") });
  let __parentId = __parentReady.data.id;
  sync({ request: Event("Intent:CreateTask:0") });
  let __bpTask0Create_title = "title_5808";
  let __created = tasksCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __parentId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __bpTask0Create_title);
  let __taskId = __created.data["task"];
  sync({ request: Event("State:TaskReady:0", { id: __taskId, title: __bpTask0Create_title }) });
  sync({ request: Event("Intent:ReadTask:0") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ waitFor: __named("Milestone:RelationsMutated") });
  sync({ request: Event("Intent:UpdateTask:0") });
  tasksUpdate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, __bpTask0Create_title);
  sync({ request: Event("Intent:ObserveUpdate:0") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ request: Event("State:UpdateObserved:0", { id: __taskId }) });
  sync({ waitFor: __named("Milestone:UpdatesObserved") });
  sync({ request: Event("Intent:DeleteTask:0") });
  tasksDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ request: Event("State:TaskDeleted:0", { id: __taskId }) });
});

bthread("crud:child:1", function() {
  let __parentReady = sync({ waitFor: __named("State:ParentReady") });
  let __parentId = __parentReady.data.id;
  sync({ request: Event("Intent:CreateTask:1") });
  let __bpTask1Create_title = "title_61221";
  let __created = tasksCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __parentId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __bpTask1Create_title);
  let __taskId = __created.data["task"];
  sync({ request: Event("State:TaskReady:1", { id: __taskId, title: __bpTask1Create_title }) });
  sync({ request: Event("Intent:ReadTask:1") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ waitFor: __named("Milestone:RelationsMutated") });
  sync({ request: Event("Intent:UpdateTask:1") });
  tasksUpdate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, __bpTask1Create_title);
  sync({ request: Event("Intent:ObserveUpdate:1") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ request: Event("State:UpdateObserved:1", { id: __taskId }) });
  sync({ waitFor: __named("Milestone:UpdatesObserved") });
  sync({ waitFor: __named("State:TaskDeleted:0") });
  sync({ request: Event("Intent:DeleteTask:1") });
  tasksDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ request: Event("State:TaskDeleted:1", { id: __taskId }) });
});

bthread("crud:child:2", function() {
  let __parentReady = sync({ waitFor: __named("State:ParentReady") });
  let __parentId = __parentReady.data.id;
  sync({ request: Event("Intent:CreateTask:2") });
  let __bpTask2Create_title = "title_30978";
  let __created = tasksCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __parentId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __bpTask2Create_title);
  let __taskId = __created.data["task"];
  sync({ request: Event("State:TaskReady:2", { id: __taskId, title: __bpTask2Create_title }) });
  sync({ request: Event("Intent:ReadTask:2") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ waitFor: __named("Milestone:RelationsMutated") });
  sync({ request: Event("Intent:UpdateTask:2") });
  tasksUpdate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, __bpTask2Create_title);
  sync({ request: Event("Intent:ObserveUpdate:2") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ request: Event("State:UpdateObserved:2", { id: __taskId }) });
  sync({ waitFor: __named("Milestone:UpdatesObserved") });
  sync({ waitFor: __named("State:TaskDeleted:1") });
  sync({ request: Event("Intent:DeleteTask:2") });
  tasksDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ request: Event("State:TaskDeleted:2", { id: __taskId }) });
});

bthread("crud:child:3", function() {
  let __parentReady = sync({ waitFor: __named("State:ParentReady") });
  let __parentId = __parentReady.data.id;
  sync({ request: Event("Intent:CreateTask:3") });
  let __bpTask3Create_title = "title_30724";
  let __created = tasksCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __parentId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __bpTask3Create_title);
  let __taskId = __created.data["task"];
  sync({ request: Event("State:TaskReady:3", { id: __taskId, title: __bpTask3Create_title }) });
  sync({ request: Event("Intent:ReadTask:3") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ waitFor: __named("Milestone:RelationsMutated") });
  sync({ request: Event("Intent:UpdateTask:3") });
  tasksUpdate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, __bpTask3Create_title);
  sync({ request: Event("Intent:ObserveUpdate:3") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ request: Event("State:UpdateObserved:3", { id: __taskId }) });
  sync({ waitFor: __named("Milestone:UpdatesObserved") });
  sync({ waitFor: __named("State:TaskDeleted:2") });
  sync({ request: Event("Intent:DeleteTask:3") });
  tasksDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ request: Event("State:TaskDeleted:3", { id: __taskId }) });
});

bthread("crud:child:4", function() {
  let __parentReady = sync({ waitFor: __named("State:ParentReady") });
  let __parentId = __parentReady.data.id;
  sync({ request: Event("Intent:CreateTask:4") });
  let __bpTask4Create_title = "title_34955";
  let __created = tasksCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __parentId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __bpTask4Create_title);
  let __taskId = __created.data["task"];
  sync({ request: Event("State:TaskReady:4", { id: __taskId, title: __bpTask4Create_title }) });
  sync({ request: Event("Intent:ReadTask:4") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ waitFor: __named("Milestone:RelationsMutated") });
  sync({ request: Event("Intent:UpdateTask:4") });
  tasksUpdate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, __bpTask4Create_title);
  sync({ request: Event("Intent:ObserveUpdate:4") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ request: Event("State:UpdateObserved:4", { id: __taskId }) });
  sync({ waitFor: __named("Milestone:UpdatesObserved") });
  sync({ waitFor: __named("State:TaskDeleted:3") });
  sync({ request: Event("Intent:DeleteTask:4") });
  tasksDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ request: Event("State:TaskDeleted:4", { id: __taskId }) });
});

bthread("crud:child:5", function() {
  let __parentReady = sync({ waitFor: __named("State:ParentReady") });
  let __parentId = __parentReady.data.id;
  sync({ request: Event("Intent:CreateTask:5") });
  let __bpTask5Create_title = "title_74829";
  let __created = tasksCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __parentId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __bpTask5Create_title);
  let __taskId = __created.data["task"];
  sync({ request: Event("State:TaskReady:5", { id: __taskId, title: __bpTask5Create_title }) });
  sync({ request: Event("Intent:ReadTask:5") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ waitFor: __named("Milestone:RelationsMutated") });
  sync({ request: Event("Intent:UpdateTask:5") });
  tasksUpdate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, __bpTask5Create_title);
  sync({ request: Event("Intent:ObserveUpdate:5") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ request: Event("State:UpdateObserved:5", { id: __taskId }) });
  sync({ waitFor: __named("Milestone:UpdatesObserved") });
  sync({ waitFor: __named("State:TaskDeleted:4") });
  sync({ request: Event("Intent:DeleteTask:5") });
  tasksDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ request: Event("State:TaskDeleted:5", { id: __taskId }) });
});

bthread("crud:child:6", function() {
  let __parentReady = sync({ waitFor: __named("State:ParentReady") });
  let __parentId = __parentReady.data.id;
  sync({ request: Event("Intent:CreateTask:6") });
  let __bpTask6Create_title = "title_79412";
  let __created = tasksCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __parentId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __bpTask6Create_title);
  let __taskId = __created.data["task"];
  sync({ request: Event("State:TaskReady:6", { id: __taskId, title: __bpTask6Create_title }) });
  sync({ request: Event("Intent:ReadTask:6") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ waitFor: __named("Milestone:RelationsMutated") });
  sync({ request: Event("Intent:UpdateTask:6") });
  tasksUpdate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, __bpTask6Create_title);
  sync({ request: Event("Intent:ObserveUpdate:6") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ request: Event("State:UpdateObserved:6", { id: __taskId }) });
  sync({ waitFor: __named("Milestone:UpdatesObserved") });
  sync({ waitFor: __named("State:TaskDeleted:5") });
  sync({ request: Event("Intent:DeleteTask:6") });
  tasksDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ request: Event("State:TaskDeleted:6", { id: __taskId }) });
});

bthread("crud:child:7", function() {
  let __parentReady = sync({ waitFor: __named("State:ParentReady") });
  let __parentId = __parentReady.data.id;
  sync({ request: Event("Intent:CreateTask:7") });
  let __bpTask7Create_title = "title_7070";
  let __created = tasksCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __parentId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __bpTask7Create_title);
  let __taskId = __created.data["task"];
  sync({ request: Event("State:TaskReady:7", { id: __taskId, title: __bpTask7Create_title }) });
  sync({ request: Event("Intent:ReadTask:7") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ waitFor: __named("Milestone:RelationsMutated") });
  sync({ request: Event("Intent:UpdateTask:7") });
  tasksUpdate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, __bpTask7Create_title);
  sync({ request: Event("Intent:ObserveUpdate:7") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ request: Event("State:UpdateObserved:7", { id: __taskId }) });
  sync({ waitFor: __named("Milestone:UpdatesObserved") });
  sync({ waitFor: __named("State:TaskDeleted:6") });
  sync({ request: Event("Intent:DeleteTask:7") });
  tasksDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ request: Event("State:TaskDeleted:7", { id: __taskId }) });
});

bthread("crud:child:8", function() {
  let __parentReady = sync({ waitFor: __named("State:ParentReady") });
  let __parentId = __parentReady.data.id;
  sync({ request: Event("Intent:CreateTask:8") });
  let __bpTask8Create_title = "title_17715";
  let __created = tasksCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __parentId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __bpTask8Create_title);
  let __taskId = __created.data["task"];
  sync({ request: Event("State:TaskReady:8", { id: __taskId, title: __bpTask8Create_title }) });
  sync({ request: Event("Intent:ReadTask:8") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ waitFor: __named("Milestone:RelationsMutated") });
  sync({ request: Event("Intent:UpdateTask:8") });
  tasksUpdate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, __bpTask8Create_title);
  sync({ request: Event("Intent:ObserveUpdate:8") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ request: Event("State:UpdateObserved:8", { id: __taskId }) });
  sync({ waitFor: __named("Milestone:UpdatesObserved") });
  sync({ waitFor: __named("State:TaskDeleted:7") });
  sync({ request: Event("Intent:DeleteTask:8") });
  tasksDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ request: Event("State:TaskDeleted:8", { id: __taskId }) });
});

bthread("crud:child:9", function() {
  let __parentReady = sync({ waitFor: __named("State:ParentReady") });
  let __parentId = __parentReady.data.id;
  sync({ request: Event("Intent:CreateTask:9") });
  let __bpTask9Create_title = "title_44847";
  let __created = tasksCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __parentId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __bpTask9Create_title);
  let __taskId = __created.data["task"];
  sync({ request: Event("State:TaskReady:9", { id: __taskId, title: __bpTask9Create_title }) });
  sync({ request: Event("Intent:ReadTask:9") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ waitFor: __named("Milestone:RelationsMutated") });
  sync({ request: Event("Intent:UpdateTask:9") });
  tasksUpdate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, __bpTask9Create_title);
  sync({ request: Event("Intent:ObserveUpdate:9") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ request: Event("State:UpdateObserved:9", { id: __taskId }) });
  sync({ waitFor: __named("Milestone:UpdatesObserved") });
  sync({ waitFor: __named("State:TaskDeleted:8") });
  sync({ request: Event("Intent:DeleteTask:9") });
  tasksDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ request: Event("State:TaskDeleted:9", { id: __taskId }) });
});

bthread("crud:child:10", function() {
  let __parentReady = sync({ waitFor: __named("State:ParentReady") });
  let __parentId = __parentReady.data.id;
  sync({ request: Event("Intent:CreateTask:10") });
  let __bpTask10Create_title = "title_88929";
  let __created = tasksCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __parentId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __bpTask10Create_title);
  let __taskId = __created.data["task"];
  sync({ request: Event("State:TaskReady:10", { id: __taskId, title: __bpTask10Create_title }) });
  sync({ request: Event("Intent:ReadTask:10") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ waitFor: __named("Milestone:RelationsMutated") });
  sync({ request: Event("Intent:UpdateTask:10") });
  tasksUpdate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, __bpTask10Create_title);
  sync({ request: Event("Intent:ObserveUpdate:10") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ request: Event("State:UpdateObserved:10", { id: __taskId }) });
  sync({ waitFor: __named("Milestone:UpdatesObserved") });
  sync({ waitFor: __named("State:TaskDeleted:9") });
  sync({ request: Event("Intent:DeleteTask:10") });
  tasksDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ request: Event("State:TaskDeleted:10", { id: __taskId }) });
});

bthread("crud:child:11", function() {
  let __parentReady = sync({ waitFor: __named("State:ParentReady") });
  let __parentId = __parentReady.data.id;
  sync({ request: Event("Intent:CreateTask:11") });
  let __bpTask11Create_title = "title_24797";
  let __created = tasksCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __parentId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __bpTask11Create_title);
  let __taskId = __created.data["task"];
  sync({ request: Event("State:TaskReady:11", { id: __taskId, title: __bpTask11Create_title }) });
  sync({ request: Event("Intent:ReadTask:11") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ waitFor: __named("Milestone:RelationsMutated") });
  sync({ request: Event("Intent:UpdateTask:11") });
  tasksUpdate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, __bpTask11Create_title);
  sync({ request: Event("Intent:ObserveUpdate:11") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ request: Event("State:UpdateObserved:11", { id: __taskId }) });
  sync({ waitFor: __named("Milestone:UpdatesObserved") });
  sync({ waitFor: __named("State:TaskDeleted:10") });
  sync({ request: Event("Intent:DeleteTask:11") });
  tasksDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __taskId, undefined);
  sync({ request: Event("State:TaskDeleted:11", { id: __taskId }) });
});

bthread("relation:edge:0", function() {
  // Register every prerequisite at once: waitFor has no history,
  // so sequential registration could miss a dependency event.
  let __dependencies = {};
  __dependencies.source = __named("State:TaskReady:0");
  __dependencies.target = __named("State:TaskReady:1");
  let __sourceId = undefined;
  let __targetId = undefined;
  while (Object.keys(__dependencies).length > 0) {
    let __dependency = sync({ waitFor: Object.values(__dependencies) });
    if (__dependencies.source && __dependencies.source.contains(__dependency)) {
      __sourceId = __dependency.data.id; delete __dependencies.source;
    } else if (__dependencies.target && __dependencies.target.contains(__dependency)) {
      __targetId = __dependency.data.id; delete __dependencies.target;
    } else if (__dependencies.previous && __dependencies.previous.contains(__dependency)) {
      delete __dependencies.previous;
    }
  }
  sync({ request: Event("Intent:CreateRelation:0", { kind: "subtask" }) });
  tasksRelationsCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "subtask", undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:ObserveRelationSource:0") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:ObserveRelationTarget:0") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined);
  sync({ request: Event("State:RelationObserved:0", { source: __sourceId, target: __targetId, kind: "subtask" }) });
  sync({ waitFor: __named("Milestone:AllRelationsObserved") });
  sync({ request: Event("Intent:DeleteRelation:0") });
  tasksRelationsDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "subtask", undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:ObserveUnlink:0") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:RecreateRelation:0") });
  tasksRelationsCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "subtask", undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("State:RelationMutated:0") });
});

bthread("relation:edge:1", function() {
  // Register every prerequisite at once: waitFor has no history,
  // so sequential registration could miss a dependency event.
  let __dependencies = {};
  __dependencies.source = __named("State:TaskReady:1");
  __dependencies.target = __named("State:TaskReady:2");
  __dependencies.previous = __named("State:RelationObserved:0");
  let __sourceId = undefined;
  let __targetId = undefined;
  while (Object.keys(__dependencies).length > 0) {
    let __dependency = sync({ waitFor: Object.values(__dependencies) });
    if (__dependencies.source && __dependencies.source.contains(__dependency)) {
      __sourceId = __dependency.data.id; delete __dependencies.source;
    } else if (__dependencies.target && __dependencies.target.contains(__dependency)) {
      __targetId = __dependency.data.id; delete __dependencies.target;
    } else if (__dependencies.previous && __dependencies.previous.contains(__dependency)) {
      delete __dependencies.previous;
    }
  }
  sync({ request: Event("Intent:CreateRelation:1", { kind: "parenttask" }) });
  tasksRelationsCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "parenttask", undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:ObserveRelationSource:1") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:ObserveRelationTarget:1") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined);
  sync({ request: Event("State:RelationObserved:1", { source: __sourceId, target: __targetId, kind: "parenttask" }) });
  sync({ waitFor: __named("Milestone:AllRelationsObserved") });
  sync({ request: Event("Intent:DeleteRelation:1") });
  tasksRelationsDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "parenttask", undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:ObserveUnlink:1") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("State:RelationMutated:1") });
});

bthread("relation:edge:2", function() {
  // Register every prerequisite at once: waitFor has no history,
  // so sequential registration could miss a dependency event.
  let __dependencies = {};
  __dependencies.source = __named("State:TaskReady:2");
  __dependencies.target = __named("State:TaskReady:3");
  __dependencies.previous = __named("State:RelationObserved:1");
  let __sourceId = undefined;
  let __targetId = undefined;
  while (Object.keys(__dependencies).length > 0) {
    let __dependency = sync({ waitFor: Object.values(__dependencies) });
    if (__dependencies.source && __dependencies.source.contains(__dependency)) {
      __sourceId = __dependency.data.id; delete __dependencies.source;
    } else if (__dependencies.target && __dependencies.target.contains(__dependency)) {
      __targetId = __dependency.data.id; delete __dependencies.target;
    } else if (__dependencies.previous && __dependencies.previous.contains(__dependency)) {
      delete __dependencies.previous;
    }
  }
  sync({ request: Event("Intent:CreateRelation:2", { kind: "related" }) });
  tasksRelationsCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "related", undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:ObserveRelationSource:2") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:ObserveRelationTarget:2") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined);
  sync({ request: Event("State:RelationObserved:2", { source: __sourceId, target: __targetId, kind: "related" }) });
  sync({ waitFor: __named("Milestone:AllRelationsObserved") });
  sync({ request: Event("Intent:DeleteRelation:2") });
  tasksRelationsDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "related", undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:ObserveUnlink:2") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:RecreateRelation:2") });
  tasksRelationsCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "related", undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("State:RelationMutated:2") });
});

bthread("relation:edge:3", function() {
  // Register every prerequisite at once: waitFor has no history,
  // so sequential registration could miss a dependency event.
  let __dependencies = {};
  __dependencies.source = __named("State:TaskReady:3");
  __dependencies.target = __named("State:TaskReady:4");
  __dependencies.previous = __named("State:RelationObserved:2");
  let __sourceId = undefined;
  let __targetId = undefined;
  while (Object.keys(__dependencies).length > 0) {
    let __dependency = sync({ waitFor: Object.values(__dependencies) });
    if (__dependencies.source && __dependencies.source.contains(__dependency)) {
      __sourceId = __dependency.data.id; delete __dependencies.source;
    } else if (__dependencies.target && __dependencies.target.contains(__dependency)) {
      __targetId = __dependency.data.id; delete __dependencies.target;
    } else if (__dependencies.previous && __dependencies.previous.contains(__dependency)) {
      delete __dependencies.previous;
    }
  }
  sync({ request: Event("Intent:CreateRelation:3", { kind: "duplicateof" }) });
  tasksRelationsCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "duplicateof", undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:ObserveRelationSource:3") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:ObserveRelationTarget:3") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined);
  sync({ request: Event("State:RelationObserved:3", { source: __sourceId, target: __targetId, kind: "duplicateof" }) });
  sync({ waitFor: __named("Milestone:AllRelationsObserved") });
  sync({ request: Event("Intent:DeleteRelation:3") });
  tasksRelationsDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "duplicateof", undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:ObserveUnlink:3") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("State:RelationMutated:3") });
});

bthread("relation:edge:4", function() {
  // Register every prerequisite at once: waitFor has no history,
  // so sequential registration could miss a dependency event.
  let __dependencies = {};
  __dependencies.source = __named("State:TaskReady:4");
  __dependencies.target = __named("State:TaskReady:5");
  __dependencies.previous = __named("State:RelationObserved:3");
  let __sourceId = undefined;
  let __targetId = undefined;
  while (Object.keys(__dependencies).length > 0) {
    let __dependency = sync({ waitFor: Object.values(__dependencies) });
    if (__dependencies.source && __dependencies.source.contains(__dependency)) {
      __sourceId = __dependency.data.id; delete __dependencies.source;
    } else if (__dependencies.target && __dependencies.target.contains(__dependency)) {
      __targetId = __dependency.data.id; delete __dependencies.target;
    } else if (__dependencies.previous && __dependencies.previous.contains(__dependency)) {
      delete __dependencies.previous;
    }
  }
  sync({ request: Event("Intent:CreateRelation:4", { kind: "duplicates" }) });
  tasksRelationsCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "duplicates", undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:ObserveRelationSource:4") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:ObserveRelationTarget:4") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined);
  sync({ request: Event("State:RelationObserved:4", { source: __sourceId, target: __targetId, kind: "duplicates" }) });
  sync({ waitFor: __named("Milestone:AllRelationsObserved") });
  sync({ request: Event("Intent:DeleteRelation:4") });
  tasksRelationsDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "duplicates", undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:ObserveUnlink:4") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:RecreateRelation:4") });
  tasksRelationsCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "duplicates", undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("State:RelationMutated:4") });
});

bthread("relation:edge:5", function() {
  // Register every prerequisite at once: waitFor has no history,
  // so sequential registration could miss a dependency event.
  let __dependencies = {};
  __dependencies.source = __named("State:TaskReady:5");
  __dependencies.target = __named("State:TaskReady:6");
  __dependencies.previous = __named("State:RelationObserved:4");
  let __sourceId = undefined;
  let __targetId = undefined;
  while (Object.keys(__dependencies).length > 0) {
    let __dependency = sync({ waitFor: Object.values(__dependencies) });
    if (__dependencies.source && __dependencies.source.contains(__dependency)) {
      __sourceId = __dependency.data.id; delete __dependencies.source;
    } else if (__dependencies.target && __dependencies.target.contains(__dependency)) {
      __targetId = __dependency.data.id; delete __dependencies.target;
    } else if (__dependencies.previous && __dependencies.previous.contains(__dependency)) {
      delete __dependencies.previous;
    }
  }
  sync({ request: Event("Intent:CreateRelation:5", { kind: "blocking" }) });
  tasksRelationsCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "blocking", undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:ObserveRelationSource:5") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:ObserveRelationTarget:5") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined);
  sync({ request: Event("State:RelationObserved:5", { source: __sourceId, target: __targetId, kind: "blocking" }) });
  sync({ waitFor: __named("Milestone:AllRelationsObserved") });
  sync({ request: Event("Intent:DeleteRelation:5") });
  tasksRelationsDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "blocking", undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:ObserveUnlink:5") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("State:RelationMutated:5") });
});

bthread("relation:edge:6", function() {
  // Register every prerequisite at once: waitFor has no history,
  // so sequential registration could miss a dependency event.
  let __dependencies = {};
  __dependencies.source = __named("State:TaskReady:6");
  __dependencies.target = __named("State:TaskReady:7");
  __dependencies.previous = __named("State:RelationObserved:5");
  let __sourceId = undefined;
  let __targetId = undefined;
  while (Object.keys(__dependencies).length > 0) {
    let __dependency = sync({ waitFor: Object.values(__dependencies) });
    if (__dependencies.source && __dependencies.source.contains(__dependency)) {
      __sourceId = __dependency.data.id; delete __dependencies.source;
    } else if (__dependencies.target && __dependencies.target.contains(__dependency)) {
      __targetId = __dependency.data.id; delete __dependencies.target;
    } else if (__dependencies.previous && __dependencies.previous.contains(__dependency)) {
      delete __dependencies.previous;
    }
  }
  sync({ request: Event("Intent:CreateRelation:6", { kind: "blocked" }) });
  tasksRelationsCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "blocked", undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:ObserveRelationSource:6") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:ObserveRelationTarget:6") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined);
  sync({ request: Event("State:RelationObserved:6", { source: __sourceId, target: __targetId, kind: "blocked" }) });
  sync({ waitFor: __named("Milestone:AllRelationsObserved") });
  sync({ request: Event("Intent:DeleteRelation:6") });
  tasksRelationsDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "blocked", undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:ObserveUnlink:6") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:RecreateRelation:6") });
  tasksRelationsCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "blocked", undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("State:RelationMutated:6") });
});

bthread("relation:edge:7", function() {
  // Register every prerequisite at once: waitFor has no history,
  // so sequential registration could miss a dependency event.
  let __dependencies = {};
  __dependencies.source = __named("State:TaskReady:7");
  __dependencies.target = __named("State:TaskReady:8");
  __dependencies.previous = __named("State:RelationObserved:6");
  let __sourceId = undefined;
  let __targetId = undefined;
  while (Object.keys(__dependencies).length > 0) {
    let __dependency = sync({ waitFor: Object.values(__dependencies) });
    if (__dependencies.source && __dependencies.source.contains(__dependency)) {
      __sourceId = __dependency.data.id; delete __dependencies.source;
    } else if (__dependencies.target && __dependencies.target.contains(__dependency)) {
      __targetId = __dependency.data.id; delete __dependencies.target;
    } else if (__dependencies.previous && __dependencies.previous.contains(__dependency)) {
      delete __dependencies.previous;
    }
  }
  sync({ request: Event("Intent:CreateRelation:7", { kind: "precedes" }) });
  tasksRelationsCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "precedes", undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:ObserveRelationSource:7") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:ObserveRelationTarget:7") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined);
  sync({ request: Event("State:RelationObserved:7", { source: __sourceId, target: __targetId, kind: "precedes" }) });
  sync({ waitFor: __named("Milestone:AllRelationsObserved") });
  sync({ request: Event("Intent:DeleteRelation:7") });
  tasksRelationsDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "precedes", undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:ObserveUnlink:7") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("State:RelationMutated:7") });
});

bthread("relation:edge:8", function() {
  // Register every prerequisite at once: waitFor has no history,
  // so sequential registration could miss a dependency event.
  let __dependencies = {};
  __dependencies.source = __named("State:TaskReady:8");
  __dependencies.target = __named("State:TaskReady:9");
  __dependencies.previous = __named("State:RelationObserved:7");
  let __sourceId = undefined;
  let __targetId = undefined;
  while (Object.keys(__dependencies).length > 0) {
    let __dependency = sync({ waitFor: Object.values(__dependencies) });
    if (__dependencies.source && __dependencies.source.contains(__dependency)) {
      __sourceId = __dependency.data.id; delete __dependencies.source;
    } else if (__dependencies.target && __dependencies.target.contains(__dependency)) {
      __targetId = __dependency.data.id; delete __dependencies.target;
    } else if (__dependencies.previous && __dependencies.previous.contains(__dependency)) {
      delete __dependencies.previous;
    }
  }
  sync({ request: Event("Intent:CreateRelation:8", { kind: "follows" }) });
  tasksRelationsCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "follows", undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:ObserveRelationSource:8") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:ObserveRelationTarget:8") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined);
  sync({ request: Event("State:RelationObserved:8", { source: __sourceId, target: __targetId, kind: "follows" }) });
  sync({ waitFor: __named("Milestone:AllRelationsObserved") });
  sync({ request: Event("Intent:DeleteRelation:8") });
  tasksRelationsDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "follows", undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:ObserveUnlink:8") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:RecreateRelation:8") });
  tasksRelationsCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "follows", undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("State:RelationMutated:8") });
});

bthread("relation:edge:9", function() {
  // Register every prerequisite at once: waitFor has no history,
  // so sequential registration could miss a dependency event.
  let __dependencies = {};
  __dependencies.source = __named("State:TaskReady:9");
  __dependencies.target = __named("State:TaskReady:10");
  __dependencies.previous = __named("State:RelationObserved:8");
  let __sourceId = undefined;
  let __targetId = undefined;
  while (Object.keys(__dependencies).length > 0) {
    let __dependency = sync({ waitFor: Object.values(__dependencies) });
    if (__dependencies.source && __dependencies.source.contains(__dependency)) {
      __sourceId = __dependency.data.id; delete __dependencies.source;
    } else if (__dependencies.target && __dependencies.target.contains(__dependency)) {
      __targetId = __dependency.data.id; delete __dependencies.target;
    } else if (__dependencies.previous && __dependencies.previous.contains(__dependency)) {
      delete __dependencies.previous;
    }
  }
  sync({ request: Event("Intent:CreateRelation:9", { kind: "copiedfrom" }) });
  tasksRelationsCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "copiedfrom", undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:ObserveRelationSource:9") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:ObserveRelationTarget:9") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined);
  sync({ request: Event("State:RelationObserved:9", { source: __sourceId, target: __targetId, kind: "copiedfrom" }) });
  sync({ waitFor: __named("Milestone:AllRelationsObserved") });
  sync({ request: Event("Intent:DeleteRelation:9") });
  tasksRelationsDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "copiedfrom", undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:ObserveUnlink:9") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("State:RelationMutated:9") });
});

bthread("relation:edge:10", function() {
  // Register every prerequisite at once: waitFor has no history,
  // so sequential registration could miss a dependency event.
  let __dependencies = {};
  __dependencies.source = __named("State:TaskReady:10");
  __dependencies.target = __named("State:TaskReady:11");
  __dependencies.previous = __named("State:RelationObserved:9");
  let __sourceId = undefined;
  let __targetId = undefined;
  while (Object.keys(__dependencies).length > 0) {
    let __dependency = sync({ waitFor: Object.values(__dependencies) });
    if (__dependencies.source && __dependencies.source.contains(__dependency)) {
      __sourceId = __dependency.data.id; delete __dependencies.source;
    } else if (__dependencies.target && __dependencies.target.contains(__dependency)) {
      __targetId = __dependency.data.id; delete __dependencies.target;
    } else if (__dependencies.previous && __dependencies.previous.contains(__dependency)) {
      delete __dependencies.previous;
    }
  }
  sync({ request: Event("Intent:CreateRelation:10", { kind: "copiedto" }) });
  tasksRelationsCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "copiedto", undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:ObserveRelationSource:10") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:ObserveRelationTarget:10") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined);
  sync({ request: Event("State:RelationObserved:10", { source: __sourceId, target: __targetId, kind: "copiedto" }) });
  sync({ waitFor: __named("Milestone:AllRelationsObserved") });
  sync({ request: Event("Intent:DeleteRelation:10") });
  tasksRelationsDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "copiedto", undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:ObserveUnlink:10") });
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("Intent:RecreateRelation:10") });
  tasksRelationsCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __targetId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "copiedto", undefined, undefined, undefined, undefined, undefined, undefined, __sourceId, undefined);
  sync({ request: Event("State:RelationMutated:10") });
});

bthread("coordinator:relations-observed", function() {
  let __pending = {};
  __pending["State:RelationObserved:0"] = __named("State:RelationObserved:0");
  __pending["State:RelationObserved:1"] = __named("State:RelationObserved:1");
  __pending["State:RelationObserved:2"] = __named("State:RelationObserved:2");
  __pending["State:RelationObserved:3"] = __named("State:RelationObserved:3");
  __pending["State:RelationObserved:4"] = __named("State:RelationObserved:4");
  __pending["State:RelationObserved:5"] = __named("State:RelationObserved:5");
  __pending["State:RelationObserved:6"] = __named("State:RelationObserved:6");
  __pending["State:RelationObserved:7"] = __named("State:RelationObserved:7");
  __pending["State:RelationObserved:8"] = __named("State:RelationObserved:8");
  __pending["State:RelationObserved:9"] = __named("State:RelationObserved:9");
  __pending["State:RelationObserved:10"] = __named("State:RelationObserved:10");
  while (Object.keys(__pending).length > 0) {
    let __seen = sync({ waitFor: Object.values(__pending) });
    if (__pending[__seen.name]) delete __pending[__seen.name];
  }
  sync({ request: Event("Milestone:AllRelationsObserved") });
});

bthread("coordinator:relations-mutated", function() {
  let __pending = {};
  __pending["State:RelationMutated:0"] = __named("State:RelationMutated:0");
  __pending["State:RelationMutated:1"] = __named("State:RelationMutated:1");
  __pending["State:RelationMutated:2"] = __named("State:RelationMutated:2");
  __pending["State:RelationMutated:3"] = __named("State:RelationMutated:3");
  __pending["State:RelationMutated:4"] = __named("State:RelationMutated:4");
  __pending["State:RelationMutated:5"] = __named("State:RelationMutated:5");
  __pending["State:RelationMutated:6"] = __named("State:RelationMutated:6");
  __pending["State:RelationMutated:7"] = __named("State:RelationMutated:7");
  __pending["State:RelationMutated:8"] = __named("State:RelationMutated:8");
  __pending["State:RelationMutated:9"] = __named("State:RelationMutated:9");
  __pending["State:RelationMutated:10"] = __named("State:RelationMutated:10");
  while (Object.keys(__pending).length > 0) {
    let __seen = sync({ waitFor: Object.values(__pending) });
    if (__pending[__seen.name]) delete __pending[__seen.name];
  }
  sync({ request: Event("Milestone:RelationsMutated") });
});

bthread("coordinator:updates-observed", function() {
  let __pending = {};
  __pending["State:UpdateObserved:0"] = __named("State:UpdateObserved:0");
  __pending["State:UpdateObserved:1"] = __named("State:UpdateObserved:1");
  __pending["State:UpdateObserved:2"] = __named("State:UpdateObserved:2");
  __pending["State:UpdateObserved:3"] = __named("State:UpdateObserved:3");
  __pending["State:UpdateObserved:4"] = __named("State:UpdateObserved:4");
  __pending["State:UpdateObserved:5"] = __named("State:UpdateObserved:5");
  __pending["State:UpdateObserved:6"] = __named("State:UpdateObserved:6");
  __pending["State:UpdateObserved:7"] = __named("State:UpdateObserved:7");
  __pending["State:UpdateObserved:8"] = __named("State:UpdateObserved:8");
  __pending["State:UpdateObserved:9"] = __named("State:UpdateObserved:9");
  __pending["State:UpdateObserved:10"] = __named("State:UpdateObserved:10");
  __pending["State:UpdateObserved:11"] = __named("State:UpdateObserved:11");
  while (Object.keys(__pending).length > 0) {
    let __seen = sync({ waitFor: Object.values(__pending) });
    if (__pending[__seen.name]) delete __pending[__seen.name];
  }
  sync({ request: Event("Milestone:UpdatesObserved") });
});

bthread("coordinator:tasks-deleted", function() {
  let __pending = {};
  __pending["State:TaskDeleted:0"] = __named("State:TaskDeleted:0");
  __pending["State:TaskDeleted:1"] = __named("State:TaskDeleted:1");
  __pending["State:TaskDeleted:2"] = __named("State:TaskDeleted:2");
  __pending["State:TaskDeleted:3"] = __named("State:TaskDeleted:3");
  __pending["State:TaskDeleted:4"] = __named("State:TaskDeleted:4");
  __pending["State:TaskDeleted:5"] = __named("State:TaskDeleted:5");
  __pending["State:TaskDeleted:6"] = __named("State:TaskDeleted:6");
  __pending["State:TaskDeleted:7"] = __named("State:TaskDeleted:7");
  __pending["State:TaskDeleted:8"] = __named("State:TaskDeleted:8");
  __pending["State:TaskDeleted:9"] = __named("State:TaskDeleted:9");
  __pending["State:TaskDeleted:10"] = __named("State:TaskDeleted:10");
  __pending["State:TaskDeleted:11"] = __named("State:TaskDeleted:11");
  while (Object.keys(__pending).length > 0) {
    let __seen = sync({ waitFor: Object.values(__pending) });
    if (__pending[__seen.name]) delete __pending[__seen.name];
  }
  sync({ request: Event("Milestone:AllTasksDeleted") });
});

bthread("coordinator:complete", function() {
  let __pending = {};
  __pending["State:ParentDeleted"] = __named("State:ParentDeleted");
  while (Object.keys(__pending).length > 0) {
    let __seen = sync({ waitFor: Object.values(__pending) });
    if (__pending[__seen.name]) delete __pending[__seen.name];
  }
  sync({ request: Event("InterleavedRelationalLifecycleComplete") });
});
