"""Render interfaces.<slug>.js: one Provengo/BPjs REST wrapper function per
usable OpenAPI operation, plus generic lifecycle-verification helper
functions per entity (derived purely from that entity's own documented
response codes -- no invented business semantics).
"""
from __future__ import annotations

import re
from typing import Dict, List

from .plan import EntityPlan, OpFunctionPlan, Plan
from .naming import js_string, safe_identifier

HEADER = '''//@provengo summon rest
// === Auto-generated interfaces for {slug} ===
// Generated by openapi_to_sbt. Do not edit by hand; regenerate instead.
//
// Uses only real, documented Provengo primitives: bare global `sync`,
// `Event`, `EventSet`, `waitFor`, `block`, `bthread` (NOT `bp.sync` /
// `bp.Event` / `bp.EventSet` -- the real `bp` object exposes only
// `bp.fork()`, `bp.log.*`, and `bp.store.*`; there is no `bp.sync` etc.
// at all). `pvg` (success/fail/log/rtv) is a runtime-provided global,
// not something this file defines. Confirmed against the official
// Provengo REST library and `bp` object documentation
// (docs.provengo.tech/ProvengoCli/0.9.5/) -- see DESIGN.md and
// FINAL_AUDIT.md for the full account of this correction, made after an
// external audit found the earlier `bp.sync`-based version would throw
// `TypeError: bp.sync is not a function` against real Provengo.
var host = (typeof host !== 'undefined') ? host : {host_js};
var port = (typeof port !== 'undefined') ? port : {port_js};
var protocol = (typeof protocol !== 'undefined') ? protocol : {protocol_js};
const svc = new RESTSession(protocol + "://" + host + ":" + port, "provengo-client", {{ headers: {{ "Content-Type": "application/json" }} }});
'''


def _url_expr(path_template: str, path_param_map: Dict[str, str]) -> str:
    parts = re.split(r"(\{[^}]+\})", path_template)
    js_parts = []
    for part in parts:
        if part.startswith("{") and part.endswith("}"):
            raw = part[1:-1]
            js_parts.append(path_param_map.get(raw, safe_identifier(raw)))
        elif part:
            js_parts.append(js_string(part))
    if not js_parts:
        return js_string(path_template)
    expr = js_parts[0]
    for p in js_parts[1:]:
        if expr.endswith('"') and p.startswith('"'):
            # merge adjacent string literals into one
            expr = expr[:-1] + p[1:]
        else:
            expr = f"{expr} + {p}"
    return expr


def _codes_list(codes: List[int]) -> str:
    return "[" + ", ".join(str(c) for c in codes) + "]"


def _body_literal(op: OpFunctionPlan) -> List[str]:
    if not op.body_props:
        return ["  var __body = undefined;"]
    lines = ["  var __body = {};"]
    for prop in sorted(op.body_props):
        js_prop = safe_identifier(prop)
        t = op.body_prop_types.get(prop, "string")
        expr = f"String({js_prop})" if t == "string" else js_prop
        lines.append(
            f'  if (typeof {js_prop} !== "undefined" && {js_prop} !== null) '
            f'{{ __body[{js_string(prop)}] = {expr}; }}'
        )
    return lines


def _params_object_literal(op: OpFunctionPlan) -> List[str]:
    """Real Provengo's documented `parameters` request option IS the
    query-string mechanism ("parameters added to the URL, in the
    parameter part i.e. after the '?'") -- there is no separate manual
    query-string-building step needed at all. An earlier version built
    its own `?a=b&c=d` string and appended it to the URL by hand, which
    worked functionally but ignored the library's own built-in support
    for this (confirmed against docs.provengo.tech's REST library
    reference)."""
    if not op.query_params:
        return []
    lines = ["  var __params = {};"]
    for q in op.query_params:
        js_q = safe_identifier(q)
        lines.append(
            f'  if (typeof {js_q} !== "undefined" && {js_q} !== null) '
            # Provengo's REST adapter converts every `parameters` value to
            # a query-string scalar and rejects raw objects. Preserve
            # complex OpenAPI query values deterministically as JSON text;
            # scalar values remain unchanged.
            f'{{ __params[{js_string(q)}] = (typeof {js_q} === "object" '
            f'? JSON.stringify({js_q}) : {js_q}); }}'
        )
    return lines


def _header_lines(op: OpFunctionPlan) -> List[str]:
    if not op.header_params:
        return []
    lines = ["  var __headers = {};"]
    for h in op.header_params:
        js_h = safe_identifier(h)
        lines.append(
            f'  if (typeof {js_h} !== "undefined" && {js_h} !== null) '
            f'{{ __headers[{js_string(h)}] = String({js_h}); }}'
        )
    return lines


def _cookie_lines(op: OpFunctionPlan) -> List[str]:
    """Cookie parameters are sent via a `Cookie` request header
    (`name=value; name2=value2`), the standard HTTP mechanism -- there is
    no separate transport for them, and no dedicated option for them in
    the real Provengo REST library either (confirmed: `options` only
    documents `headers`/`parameters`/`body`/`expectedResponseCodes`/
    `callback`). Found missing entirely (not wired, not even reported as
    excluded) on a full re-audit against ACCEPTANCE_CRITERIA.md's "cover
    every ... parameter location ... or list a justified exclusion"
    requirement."""
    if not op.cookie_params:
        return []
    lines = ["  var __cookieParts = [];"]
    for c in op.cookie_params:
        js_c = safe_identifier(c)
        lines.append(
            f'  if (typeof {js_c} !== "undefined" && {js_c} !== null) '
            f'{{ __cookieParts.push({js_string(c)} + "=" + String({js_c})); }}'
        )
    lines.append(
        '  if (__cookieParts.length > 0) { '
        'if (typeof __headers === "undefined") { var __headers = {}; } '
        '__headers["Cookie"] = __cookieParts.join("; "); }'
    )
    return lines


def render_op_function(op: OpFunctionPlan) -> str:
    lines = [f"function {op.js_name}({', '.join(op.params)}) {{"]
    url_expr = _url_expr(op.op.path, op.path_param_map)
    # NOTE: every helper variable this function declares for its own
    # internal bookkeeping (URL, description, body, ...) is prefixed with
    # `__` specifically so it can never collide with a real OpenAPI field
    # name passed in as a parameter (see DESIGN.md / REAL_SUT_VALIDATION.md
    # bug 13 for why this matters: `var description = ...` inside a
    # function where `description` is already a parameter reassigns the
    # parameter instead of declaring a new variable).
    lines.append(f"  var __url = {url_expr};")

    desc = op.description_base
    suffix_param = None
    if op.kind in ("list", "create", "update", "delete", "action"):
        for candidate in op.params:
            if candidate in op.path_param_map.values() or candidate == "id":
                suffix_param = candidate
                break
    if suffix_param:
        lines.append(f'  var __description = {js_string(desc + " ")} + {suffix_param};')
    else:
        lines.append(f"  var __description = {js_string(desc)};")
    # `bp.log.info` is real and documented (docs.provengo.tech/.../dsls/
    # bp-object.html); an earlier version invented a non-existent
    # `parameters: { description: ... }` request option to carry this
    # text -- but real Provengo's `parameters` option IS the query
    # string, so that would have sent a literal `?description=...` query
    # parameter to the server on every single call.
    lines.append("  bp.log.info(__description);")

    method = op.op.method.lower()
    has_body = method in ("post", "put", "patch") and op.op.request_body is not None

    if op.query_params:
        lines.extend(_params_object_literal(op))

    if op.header_params:
        # `headers` is a real, documented option. The exact shape is
        # confirmed against docs.provengo.tech's REST library reference.
        lines.extend(_header_lines(op))

    if op.cookie_params:
        lines.extend(_cookie_lines(op))

    if has_body:
        lines.extend(_body_literal(op))

    all_codes = sorted(set(op.success_codes) | set(op.error_codes))
    codes_js = _codes_list(all_codes) if all_codes else "[]"

    # A Provengo REST callback is executed by the actuator, outside the
    # requesting b-thread. It may inspect/mutate captured values, but it
    # must not call sync()/request()/waitFor(): doing so raises
    # BPjsOutsideOfBThreadException in the real engine. always installs
    # a callback so the completion event carries facts OBSERVED from the
    # actual HTTP response (response.code + parsed response.body), rather
    # than only the request intent. This is crucial for A-2-A evaluation:
    # runtime story dependencies may consume HTTP-derived facts, while the
    # immutable proxy trace remains the external evidence/oracle.
    needs_callback = True
    lines.append("  var __httpCode = null;")
    lines.append("  var __httpResponse = null;")

    # V33: create-like operations may expose server-assigned identifiers only
    # when the REST callback executes. Reuse the existing key argument as a
    # generic opt-in carrier: ``__PVG_RTV__:<name>`` asks the callback to copy
    # the observed response key into Provengo's runtime-variable store.
    if op.server_assigned_key_fields:
        for jsfield in op.server_assigned_key_fields:
            lines.append(
                f'  var __rtv_{jsfield} = (typeof {jsfield} === "string" && '
                f'{jsfield}.indexOf("__PVG_RTV__:") === 0) ? '
                f'{jsfield}.substring(12) : null;'
            )

    call_opts = []
    if has_body:
        call_opts.append("body: JSON.stringify(__body)")
    if op.query_params:
        call_opts.append("parameters: __params")
    if op.header_params or op.cookie_params:
        call_opts.append("headers: __headers")
    call_opts.append(f"expectedResponseCodes: {codes_js}")

    if needs_callback:
        # Official Provengo REST documentation defines response fields
        # `code`, `headers`, `version`, and `body`; body is a string. Keep
        # the parsed JSON when possible and the raw body otherwise.
        callback_lines = [
            "    __httpCode = response.code;",
            "    var __parsed = null;",
            "    try { __parsed = JSON.parse(response.body); } catch (e) { /* non-JSON response body */ }",
            "    __httpResponse = (__parsed !== null) ? __parsed : response.body;",
        ]
        if op.server_assigned_key_fields:
            resp_field = op.server_assigned_response_field or "id"
            for jsfield in op.server_assigned_key_fields:
                callback_lines.append(
                    f'    if (__parsed && __parsed[{js_string(resp_field)}] !== undefined) {{'
                )
                callback_lines.append(
                    f'      if (__rtv_{jsfield}) {{ pvg.rtv.set(__rtv_{jsfield}, __parsed[{js_string(resp_field)}]); }}'
                )
                callback_lines.append(
                    f'      {jsfield} = __parsed[{js_string(resp_field)}];'
                )
                callback_lines.append('    }')
        call_opts.append("callback: function(response) {\n" + "\n".join(callback_lines) + "\n  }")

    opts_js = "{ " + ", ".join(call_opts) + " }"
    lines.append(f"  svc.{method}(__url, {opts_js});")

    # svc.<method>() performs the b-thread's REST synchronization and
    # returns only after actuation/validation. Publish the semantic
    # completion event here, in b-thread context, never in the actuator
    # callback (which real Provengo executes outside a b-thread).
    has_completion_data = op.emits_done_event and (op.success_codes or op.kind == "action")
    if has_completion_data:
        data_pairs = ", ".join(f'{js_string(p)}: {p}' for p in op.params)
        if data_pairs:
            data_pairs += ', '
        data_pairs += '"__httpCode": __httpCode, "__httpResponse": __httpResponse'
        if op.entity_key:
            data_pairs += f', "__entityKey": {js_string(op.entity_key)}'
        # Materialize the completion payload once and return the exact same
        # object to the calling story.  A caller cannot reliably wait for its
        # own Done event *after* this function returns because that event has
        # already been selected inside this function.  Returning the payload
        # directly preserves per-story identity even when many same-entity
        # creators are active concurrently.
        lines.append(f'  var __completionData = {{{data_pairs}}};')
        lines.append(
            f'  sync({{ request: Event("Done: " + __description, __completionData) }});'
        )

    if op.has_default_response:
        lines.append(f"  // NOTE: OpenAPI declares a 'default' response for this operation;")
        lines.append(f"  // it is not mapped to a specific expectedResponseCodes entry (see generation_report.json).")

    # expose the actual observed HTTP response to a caller that wants to
    # build semantic state from the wire. Generic generated CRUD stories may
    # ignore this return value; semantic overlays can chain on it without
    # consulting SUT-internal logs/events.
    if has_completion_data:
        lines.append('  return { code: __httpCode, body: __httpResponse, data: __completionData };')
    else:
        lines.append('  return { code: __httpCode, body: __httpResponse };')
    lines.append("}")
    return "\n".join(lines)


def render_entity_helpers(ep: EntityPlan) -> List[str]:
    """Generic per-entity helper functions, generated only when the
    underlying operation and response codes actually exist in the
    contract."""
    out: List[str] = []
    plural = ep.entity.plural_display_name
    key_fields = ep.key.fields
    single_key = key_fields[0] if len(key_fields) == 1 else None
    all_params = ep.fields

    if ep.create_op and ep.create_op.error_codes:
        fn = f"tryToAddExisting{plural}"
        params_sig = ", ".join(all_params)
        lines = [f"function {fn}({params_sig}) {{"]
        lines.append(f"  var __url = {js_string(ep.entity.collection_path)};")
        suffix = f" + {single_key}" if single_key and single_key in all_params else ""
        lines.append(f'  var __description = {js_string("Try Add Existing " + plural + " ")}{suffix};')
        lines.append("  bp.log.info(__description);")
        lines.extend(_body_literal(ep.create_op))
        lines.append(
            f"  svc.post(__url, {{ body: JSON.stringify(__body), "
            f"expectedResponseCodes: {_codes_list(ep.create_op.error_codes)} }});"
        )
        lines.append("}")
        out.append("\n".join(lines))
    elif ep.create_op:
        out.append(f"// tryToAddExisting{plural} skipped: create operation documents no error response codes.")

    if ep.get_op:
        success_200 = [c for c in ep.get_op.success_codes if c == 200] or ep.get_op.success_codes
        params_sig = ", ".join(all_params)
        fn = f"verify{plural}Exists"
        lines = [f"function {fn}({params_sig}) {{"]
        lines.append(f"  var __url = {_url_expr(ep.get_op.op.path, ep.get_op.path_param_map)};")
        # `pvg.success`/`pvg.fail` must be called from inside the async
        # `callback` -- REST calls are dispatched asynchronously, so
        # calling them immediately after `svc.get(...)` (as an earlier
        # version did) would unconditionally report success before the
        # response (or any response at all) had actually arrived.
        lines.append(
            f'  svc.get(__url, {{ expectedResponseCodes: {_codes_list(success_200)}, '
            f'callback: function(response) {{ pvg.success({js_string(plural + " found")}); }} }});'
        )
        lines.append("}")
        out.append("\n".join(lines))

        if 404 in ep.get_op.error_codes:
            fn2 = f"verify{plural}DoesNotExist"
            lines = [f"function {fn2}({params_sig}) {{"]
            lines.append(f"  var __url = {_url_expr(ep.get_op.op.path, ep.get_op.path_param_map)};")
            lines.append(
                f'  svc.get(__url, {{ expectedResponseCodes: [404], '
                f'callback: function(response) {{ pvg.success({js_string(plural + " not found")}); }} }});'
            )
            lines.append("}")
            out.append("\n".join(lines))
        else:
            out.append(f"// verify{plural}DoesNotExist skipped: GET /{{id}} does not document a 404 response.")
    else:
        out.append(f"// verify{plural}Exists / verify{plural}DoesNotExist skipped: no GET item operation detected.")

    if ep.delete_op:
        params_sig = ", ".join(all_params)
        fn = f"tryToDeleteANonExisting{plural}"
        lines = [f"function {fn}({params_sig}) {{"]
        lines.append(f"  var __url = {_url_expr(ep.delete_op.op.path, ep.delete_op.path_param_map)};")
        all_codes = sorted(set(ep.delete_op.success_codes) | set(ep.delete_op.error_codes))
        lines.append(f'  svc.delete(__url, {{ expectedResponseCodes: {_codes_list(all_codes)} }});')
        lines.append("}")
        out.append("\n".join(lines))

        fn3 = f"matchDeleted{plural}"
        base = ep.delete_op.description_base
        entity_key_js = js_string(ep.entity.key)
        out.append(
            f'function {fn3}() {{\n'
            f'  return EventSet({js_string("Delete " + plural)}, function(e) {{\n'
            f'      return e.name.startsWith("Done: " + {js_string(base)}) && '
            f'e.data && e.data["__entityKey"] === {entity_key_js};\n'
            f'  }});\n'
            f'}}'
        )

    if ep.create_op:
        base = ep.create_op.description_base
        entity_key_js = js_string(ep.entity.key)
        fn = f"waitFor{plural}Added"
        params_sig = ", ".join(all_params)
        out.append(
            f'function {fn}({params_sig}) {{\n'
            f'  waitFor(matchAny{plural}Added());\n'
            f'}}'
        )
        fn2 = f"matchAny{plural}Added"
        out.append(
            f'function {fn2}() {{\n'
            f'  return EventSet({js_string("Any " + plural + " Added")}, function(e) {{\n'
            f'      return e.name.startsWith("Done: " + {js_string(base)}) && '
            f'e.data && e.data["__entityKey"] === {entity_key_js};\n'
            f'  }});\n'
            f'}}'
        )

    return out


def render_interfaces(plan: Plan, slug: str, host: str, port: int, protocol: str) -> str:
    parts = [HEADER.format(
        slug=slug, host_js=js_string(host), port_js=str(port), protocol_js=js_string(protocol),
    )]

    for ep in plan.entities:
        for op in ep.ops:
            parts.append(render_op_function(op))
        parts.extend(render_entity_helpers(ep))

    for op in plan.standalone_ops:
        parts.append(render_op_function(op))

    return "\n\n".join(parts) + "\n"
