//@provengo summon rest
// === Auto-generated interfaces for vikunja ===
// Generated by openapi_to_sbt. Do not edit by hand; regenerate instead.
//
// Uses only real, documented Provengo primitives: bare global `sync`,
// `Event`, `EventSet`, `waitFor`, `block`, `bthread` (NOT `bp.sync` /
// `bp.Event` / `bp.EventSet` -- the real `bp` object exposes only
// `bp.fork()`, `bp.log.*`, and `bp.store.*`; there is no `bp.sync` etc.
// at all). `pvg` (success/fail/log/rtv) is a runtime-provided global,
// not something this file defines. Confirmed against the official
// Provengo REST library and `bp` object documentation
// (docs.provengo.tech/ProvengoCli/0.9.5/) -- see DESIGN.md and
// FINAL_AUDIT.md for the full account of this correction, made after an
// external audit found the earlier `bp.sync`-based version would throw
// `TypeError: bp.sync is not a function` against real Provengo.
var host = (typeof host !== 'undefined') ? host : "127.0.0.1";
var port = (typeof port !== 'undefined') ? port : 3457;
var protocol = (typeof protocol !== 'undefined') ? protocol : "http";
const svc = new RESTSession(protocol + "://" + host + ":" + port, "provengo-client", { headers: { "Content-Type": "application/json" } });


function labelsList(ifMatch, ifModifiedSince, ifNoneMatch, ifUnmodifiedSince, createdBy, description, format, hexColor, id, page, perPage, q, title) {
  var __url = "/labels";
  var __description = "List labels " + id;
  bp.log.info(__description);
  var __params = {};
  if (typeof page !== "undefined" && page !== null) { __params["page"] = (typeof page === "object" ? JSON.stringify(page) : page); }
  if (typeof perPage !== "undefined" && perPage !== null) { __params["per_page"] = (typeof perPage === "object" ? JSON.stringify(perPage) : perPage); }
  if (typeof q !== "undefined" && q !== null) { __params["q"] = (typeof q === "object" ? JSON.stringify(q) : q); }
  if (typeof format !== "undefined" && format !== null) { __params["format"] = (typeof format === "object" ? JSON.stringify(format) : format); }
  var __httpCode = null;
  var __httpResponse = null;
  svc.get(__url, { parameters: __params, expectedResponseCodes: [200], callback: function(response) {
    __httpCode = response.code;
    var __parsed = null;
    try { __parsed = JSON.parse(response.body); } catch (e) { /* non-JSON response body */ }
    __httpResponse = (__parsed !== null) ? __parsed : response.body;
  } });
  // NOTE: OpenAPI declares a 'default' response for this operation;
  // it is not mapped to a specific expectedResponseCodes entry (see generation_report.json).
  return { code: __httpCode, body: __httpResponse };
}

function labelsCreate(ifMatch, ifModifiedSince, ifNoneMatch, ifUnmodifiedSince, createdBy, description, format, hexColor, id, page, perPage, q, title) {
  var __url = "/labels";
  var __description = "Create a label " + id;
  bp.log.info(__description);
  var __params = {};
  if (typeof format !== "undefined" && format !== null) { __params["format"] = (typeof format === "object" ? JSON.stringify(format) : format); }
  var __body = {
    "created_by": createdBy,
    "description": String(description),
    "hex_color": String(hexColor),
    "title": String(title),
};
  var __httpCode = null;
  var __httpResponse = null;
  var __rtv_id = (typeof id === "string" && id.indexOf("__PVG_RTV__:") === 0) ? id.substring(12) : null;
  svc.post(__url, { body: JSON.stringify(__body), parameters: __params, expectedResponseCodes: [201], callback: function(response) {
    __httpCode = response.code;
    var __parsed = null;
    try { __parsed = JSON.parse(response.body); } catch (e) { /* non-JSON response body */ }
    __httpResponse = (__parsed !== null) ? __parsed : response.body;
    if (__parsed && __parsed["id"] !== undefined) {
      if (__rtv_id) { pvg.rtv.set(__rtv_id, __parsed["id"]); }
      id = __parsed["id"];
    }
  } });
  var __completionData = {"ifMatch": ifMatch, "ifModifiedSince": ifModifiedSince, "ifNoneMatch": ifNoneMatch, "ifUnmodifiedSince": ifUnmodifiedSince, "createdBy": createdBy, "description": description, "format": format, "hexColor": hexColor, "id": id, "page": page, "perPage": perPage, "q": q, "title": title, "__httpCode": __httpCode, "__httpResponse": __httpResponse, "__entityKey": "labels"};
  sync({ request: Event("Done: " + __description, __completionData) });
  // NOTE: OpenAPI declares a 'default' response for this operation;
  // it is not mapped to a specific expectedResponseCodes entry (see generation_report.json).
  return { code: __httpCode, body: __httpResponse, data: __completionData };
}

function labelsDelete(ifMatch, ifModifiedSince, ifNoneMatch, ifUnmodifiedSince, createdBy, description, format, hexColor, id, page, perPage, q, title) {
  var __url = "/labels/" + id;
  var __description = "Delete a label " + id;
  bp.log.info(__description);
  var __httpCode = null;
  var __httpResponse = null;
  svc.delete(__url, { expectedResponseCodes: [204], callback: function(response) {
    __httpCode = response.code;
    var __parsed = null;
    try { __parsed = JSON.parse(response.body); } catch (e) { /* non-JSON response body */ }
    __httpResponse = (__parsed !== null) ? __parsed : response.body;
  } });
  var __completionData = {"ifMatch": ifMatch, "ifModifiedSince": ifModifiedSince, "ifNoneMatch": ifNoneMatch, "ifUnmodifiedSince": ifUnmodifiedSince, "createdBy": createdBy, "description": description, "format": format, "hexColor": hexColor, "id": id, "page": page, "perPage": perPage, "q": q, "title": title, "__httpCode": __httpCode, "__httpResponse": __httpResponse, "__entityKey": "labels"};
  sync({ request: Event("Done: " + __description, __completionData) });
  // NOTE: OpenAPI declares a 'default' response for this operation;
  // it is not mapped to a specific expectedResponseCodes entry (see generation_report.json).
  return { code: __httpCode, body: __httpResponse, data: __completionData };
}

function labelsRead(ifMatch, ifModifiedSince, ifNoneMatch, ifUnmodifiedSince, createdBy, description, format, hexColor, id, page, perPage, q, title) {
  var __url = "/labels/" + id;
  var __description = "Get a label";
  bp.log.info(__description);
  var __params = {};
  if (typeof format !== "undefined" && format !== null) { __params["format"] = (typeof format === "object" ? JSON.stringify(format) : format); }
  var __headers = {};
  if (typeof ifMatch !== "undefined" && ifMatch !== null) { __headers["If-Match"] = String(ifMatch); }
  if (typeof ifNoneMatch !== "undefined" && ifNoneMatch !== null) { __headers["If-None-Match"] = String(ifNoneMatch); }
  if (typeof ifModifiedSince !== "undefined" && ifModifiedSince !== null) { __headers["If-Modified-Since"] = String(ifModifiedSince); }
  if (typeof ifUnmodifiedSince !== "undefined" && ifUnmodifiedSince !== null) { __headers["If-Unmodified-Since"] = String(ifUnmodifiedSince); }
  var __httpCode = null;
  var __httpResponse = null;
  svc.get(__url, { parameters: __params, headers: __headers, expectedResponseCodes: [200], callback: function(response) {
    __httpCode = response.code;
    var __parsed = null;
    try { __parsed = JSON.parse(response.body); } catch (e) { /* non-JSON response body */ }
    __httpResponse = (__parsed !== null) ? __parsed : response.body;
  } });
  // NOTE: OpenAPI declares a 'default' response for this operation;
  // it is not mapped to a specific expectedResponseCodes entry (see generation_report.json).
  return { code: __httpCode, body: __httpResponse };
}

function patchLabelsRead(ifMatch, ifModifiedSince, ifNoneMatch, ifUnmodifiedSince, createdBy, description, format, hexColor, id, page, perPage, q, title) {
  var __url = "/labels/" + id;
  var __description = "Update a label (partial) " + id;
  bp.log.info(__description);
  var __body = undefined;
  var __httpCode = null;
  var __httpResponse = null;
  svc.patch(__url, { body: JSON.stringify(__body), expectedResponseCodes: [200], callback: function(response) {
    __httpCode = response.code;
    var __parsed = null;
    try { __parsed = JSON.parse(response.body); } catch (e) { /* non-JSON response body */ }
    __httpResponse = (__parsed !== null) ? __parsed : response.body;
  } });
  var __completionData = {"ifMatch": ifMatch, "ifModifiedSince": ifModifiedSince, "ifNoneMatch": ifNoneMatch, "ifUnmodifiedSince": ifUnmodifiedSince, "createdBy": createdBy, "description": description, "format": format, "hexColor": hexColor, "id": id, "page": page, "perPage": perPage, "q": q, "title": title, "__httpCode": __httpCode, "__httpResponse": __httpResponse, "__entityKey": "labels"};
  sync({ request: Event("Done: " + __description, __completionData) });
  // NOTE: OpenAPI declares a 'default' response for this operation;
  // it is not mapped to a specific expectedResponseCodes entry (see generation_report.json).
  return { code: __httpCode, body: __httpResponse, data: __completionData };
}

function labelsUpdate(ifMatch, ifModifiedSince, ifNoneMatch, ifUnmodifiedSince, createdBy, description, format, hexColor, id, page, perPage, q, title) {
  var __url = "/labels/" + id;
  var __description = "Update a label " + id;
  bp.log.info(__description);
  var __params = {};
  if (typeof format !== "undefined" && format !== null) { __params["format"] = (typeof format === "object" ? JSON.stringify(format) : format); }
  var __body = {
    "created_by": createdBy,
    "description": String(description),
    "hex_color": String(hexColor),
    "title": String(title),
};
  var __httpCode = null;
  var __httpResponse = null;
  svc.put(__url, { body: JSON.stringify(__body), parameters: __params, expectedResponseCodes: [200], callback: function(response) {
    __httpCode = response.code;
    var __parsed = null;
    try { __parsed = JSON.parse(response.body); } catch (e) { /* non-JSON response body */ }
    __httpResponse = (__parsed !== null) ? __parsed : response.body;
  } });
  var __completionData = {"ifMatch": ifMatch, "ifModifiedSince": ifModifiedSince, "ifNoneMatch": ifNoneMatch, "ifUnmodifiedSince": ifUnmodifiedSince, "createdBy": createdBy, "description": description, "format": format, "hexColor": hexColor, "id": id, "page": page, "perPage": perPage, "q": q, "title": title, "__httpCode": __httpCode, "__httpResponse": __httpResponse, "__entityKey": "labels"};
  sync({ request: Event("Done: " + __description, __completionData) });
  // NOTE: OpenAPI declares a 'default' response for this operation;
  // it is not mapped to a specific expectedResponseCodes entry (see generation_report.json).
  return { code: __httpCode, body: __httpResponse, data: __completionData };
}

// tryToAddExistingPaginatedLabelWithTaskIDs skipped: create operation documents no error response codes.

function verifyPaginatedLabelWithTaskIDsExists(ifMatch, ifModifiedSince, ifNoneMatch, ifUnmodifiedSince, createdBy, description, format, hexColor, id, page, perPage, q, title) {
  var __url = "/labels/" + id;
  svc.get(__url, { expectedResponseCodes: [200], callback: function(response) { pvg.success("PaginatedLabelWithTaskIDs found"); } });
}

// verifyPaginatedLabelWithTaskIDsDoesNotExist skipped: GET /{id} does not document a 404 response.

function tryToDeleteANonExistingPaginatedLabelWithTaskIDs(ifMatch, ifModifiedSince, ifNoneMatch, ifUnmodifiedSince, createdBy, description, format, hexColor, id, page, perPage, q, title) {
  var __url = "/labels/" + id;
  svc.delete(__url, { expectedResponseCodes: [204] });
}

function matchDeletedPaginatedLabelWithTaskIDs() {
  return EventSet("Delete PaginatedLabelWithTaskIDs", function(e) {
      return e.name.startsWith("Done: " + "Delete a label") && e.data && e.data["__entityKey"] === "labels";
  });
}

function waitForPaginatedLabelWithTaskIDsAdded(ifMatch, ifModifiedSince, ifNoneMatch, ifUnmodifiedSince, createdBy, description, format, hexColor, id, page, perPage, q, title) {
  waitFor(matchAnyPaginatedLabelWithTaskIDsAdded());
}

function matchAnyPaginatedLabelWithTaskIDsAdded() {
  return EventSet("Any PaginatedLabelWithTaskIDs Added", function(e) {
      return e.name.startsWith("Done: " + "Create a label") && e.data && e.data["__entityKey"] === "labels";
  });
}

function projectsList(description, expand, format, hexColor, id, identifier, isArchived, isFavorite, owner, page, parentProjectId, perPage, position, q, subscription, title) {
  var __url = "/projects";
  var __description = "List projects " + id;
  bp.log.info(__description);
  var __params = {};
  if (typeof page !== "undefined" && page !== null) { __params["page"] = (typeof page === "object" ? JSON.stringify(page) : page); }
  if (typeof perPage !== "undefined" && perPage !== null) { __params["per_page"] = (typeof perPage === "object" ? JSON.stringify(perPage) : perPage); }
  if (typeof q !== "undefined" && q !== null) { __params["q"] = (typeof q === "object" ? JSON.stringify(q) : q); }
  if (typeof expand !== "undefined" && expand !== null) { __params["expand"] = (typeof expand === "object" ? JSON.stringify(expand) : expand); }
  if (typeof isArchived !== "undefined" && isArchived !== null) { __params["is_archived"] = (typeof isArchived === "object" ? JSON.stringify(isArchived) : isArchived); }
  if (typeof format !== "undefined" && format !== null) { __params["format"] = (typeof format === "object" ? JSON.stringify(format) : format); }
  var __httpCode = null;
  var __httpResponse = null;
  svc.get(__url, { parameters: __params, expectedResponseCodes: [200], callback: function(response) {
    __httpCode = response.code;
    var __parsed = null;
    try { __parsed = JSON.parse(response.body); } catch (e) { /* non-JSON response body */ }
    __httpResponse = (__parsed !== null) ? __parsed : response.body;
  } });
  // NOTE: OpenAPI declares a 'default' response for this operation;
  // it is not mapped to a specific expectedResponseCodes entry (see generation_report.json).
  return { code: __httpCode, body: __httpResponse };
}

function projectsCreate(description, expand, format, hexColor, id, identifier, isArchived, isFavorite, owner, page, parentProjectId, perPage, position, q, subscription, title) {
  var __url = "/projects";
  var __description = "Create a project " + id;
  bp.log.info(__description);
  var __params = {};
  if (typeof format !== "undefined" && format !== null) { __params["format"] = (typeof format === "object" ? JSON.stringify(format) : format); }
  var __body = {
    "description": String(description),
    "hex_color": String(hexColor),
    "identifier": String(identifier),
    "is_archived": isArchived,
    "is_favorite": isFavorite,
    "owner": owner,
    "parent_project_id": parentProjectId,
    "position": position,
    "subscription": subscription,
    "title": String(title),
};
  var __httpCode = null;
  var __httpResponse = null;
  var __rtv_id = (typeof id === "string" && id.indexOf("__PVG_RTV__:") === 0) ? id.substring(12) : null;
  svc.post(__url, { body: JSON.stringify(__body), parameters: __params, expectedResponseCodes: [201], callback: function(response) {
    __httpCode = response.code;
    var __parsed = null;
    try { __parsed = JSON.parse(response.body); } catch (e) { /* non-JSON response body */ }
    __httpResponse = (__parsed !== null) ? __parsed : response.body;
    if (__parsed && __parsed["id"] !== undefined) {
      if (__rtv_id) { pvg.rtv.set(__rtv_id, __parsed["id"]); }
      id = __parsed["id"];
    }
  } });
  var __completionData = {"description": description, "expand": expand, "format": format, "hexColor": hexColor, "id": id, "identifier": identifier, "isArchived": isArchived, "isFavorite": isFavorite, "owner": owner, "page": page, "parentProjectId": parentProjectId, "perPage": perPage, "position": position, "q": q, "subscription": subscription, "title": title, "__httpCode": __httpCode, "__httpResponse": __httpResponse, "__entityKey": "projects"};
  sync({ request: Event("Done: " + __description, __completionData) });
  // NOTE: OpenAPI declares a 'default' response for this operation;
  // it is not mapped to a specific expectedResponseCodes entry (see generation_report.json).
  return { code: __httpCode, body: __httpResponse, data: __completionData };
}

function projectsDelete(description, expand, format, hexColor, id, identifier, isArchived, isFavorite, owner, page, parentProjectId, perPage, position, q, subscription, title) {
  var __url = "/projects/" + id;
  var __description = "Delete a project " + id;
  bp.log.info(__description);
  var __httpCode = null;
  var __httpResponse = null;
  svc.delete(__url, { expectedResponseCodes: [204], callback: function(response) {
    __httpCode = response.code;
    var __parsed = null;
    try { __parsed = JSON.parse(response.body); } catch (e) { /* non-JSON response body */ }
    __httpResponse = (__parsed !== null) ? __parsed : response.body;
  } });
  var __completionData = {"description": description, "expand": expand, "format": format, "hexColor": hexColor, "id": id, "identifier": identifier, "isArchived": isArchived, "isFavorite": isFavorite, "owner": owner, "page": page, "parentProjectId": parentProjectId, "perPage": perPage, "position": position, "q": q, "subscription": subscription, "title": title, "__httpCode": __httpCode, "__httpResponse": __httpResponse, "__entityKey": "projects"};
  sync({ request: Event("Done: " + __description, __completionData) });
  // NOTE: OpenAPI declares a 'default' response for this operation;
  // it is not mapped to a specific expectedResponseCodes entry (see generation_report.json).
  return { code: __httpCode, body: __httpResponse, data: __completionData };
}

function projectsRead(description, expand, format, hexColor, id, identifier, isArchived, isFavorite, owner, page, parentProjectId, perPage, position, q, subscription, title) {
  var __url = "/projects/" + id;
  var __description = "Get a project";
  bp.log.info(__description);
  var __params = {};
  if (typeof format !== "undefined" && format !== null) { __params["format"] = (typeof format === "object" ? JSON.stringify(format) : format); }
  var __httpCode = null;
  var __httpResponse = null;
  svc.get(__url, { parameters: __params, expectedResponseCodes: [200], callback: function(response) {
    __httpCode = response.code;
    var __parsed = null;
    try { __parsed = JSON.parse(response.body); } catch (e) { /* non-JSON response body */ }
    __httpResponse = (__parsed !== null) ? __parsed : response.body;
  } });
  // NOTE: OpenAPI declares a 'default' response for this operation;
  // it is not mapped to a specific expectedResponseCodes entry (see generation_report.json).
  return { code: __httpCode, body: __httpResponse };
}

function patchProjectsRead(description, expand, format, hexColor, id, identifier, isArchived, isFavorite, owner, page, parentProjectId, perPage, position, q, subscription, title) {
  var __url = "/projects/" + id;
  var __description = "Update a project (partial) " + id;
  bp.log.info(__description);
  var __body = undefined;
  var __httpCode = null;
  var __httpResponse = null;
  svc.patch(__url, { body: JSON.stringify(__body), expectedResponseCodes: [200], callback: function(response) {
    __httpCode = response.code;
    var __parsed = null;
    try { __parsed = JSON.parse(response.body); } catch (e) { /* non-JSON response body */ }
    __httpResponse = (__parsed !== null) ? __parsed : response.body;
  } });
  var __completionData = {"description": description, "expand": expand, "format": format, "hexColor": hexColor, "id": id, "identifier": identifier, "isArchived": isArchived, "isFavorite": isFavorite, "owner": owner, "page": page, "parentProjectId": parentProjectId, "perPage": perPage, "position": position, "q": q, "subscription": subscription, "title": title, "__httpCode": __httpCode, "__httpResponse": __httpResponse, "__entityKey": "projects"};
  sync({ request: Event("Done: " + __description, __completionData) });
  // NOTE: OpenAPI declares a 'default' response for this operation;
  // it is not mapped to a specific expectedResponseCodes entry (see generation_report.json).
  return { code: __httpCode, body: __httpResponse, data: __completionData };
}

function projectsUpdate(description, expand, format, hexColor, id, identifier, isArchived, isFavorite, owner, page, parentProjectId, perPage, position, q, subscription, title) {
  var __url = "/projects/" + id;
  var __description = "Update a project " + id;
  bp.log.info(__description);
  var __params = {};
  if (typeof format !== "undefined" && format !== null) { __params["format"] = (typeof format === "object" ? JSON.stringify(format) : format); }
  var __body = {
    "description": String(description),
    "hex_color": String(hexColor),
    "identifier": String(identifier),
    "is_archived": isArchived,
    "is_favorite": isFavorite,
    "owner": owner,
    "parent_project_id": parentProjectId,
    "position": position,
    "subscription": subscription,
    "title": String(title),
};
  var __httpCode = null;
  var __httpResponse = null;
  svc.put(__url, { body: JSON.stringify(__body), parameters: __params, expectedResponseCodes: [200], callback: function(response) {
    __httpCode = response.code;
    var __parsed = null;
    try { __parsed = JSON.parse(response.body); } catch (e) { /* non-JSON response body */ }
    __httpResponse = (__parsed !== null) ? __parsed : response.body;
  } });
  var __completionData = {"description": description, "expand": expand, "format": format, "hexColor": hexColor, "id": id, "identifier": identifier, "isArchived": isArchived, "isFavorite": isFavorite, "owner": owner, "page": page, "parentProjectId": parentProjectId, "perPage": perPage, "position": position, "q": q, "subscription": subscription, "title": title, "__httpCode": __httpCode, "__httpResponse": __httpResponse, "__entityKey": "projects"};
  sync({ request: Event("Done: " + __description, __completionData) });
  // NOTE: OpenAPI declares a 'default' response for this operation;
  // it is not mapped to a specific expectedResponseCodes entry (see generation_report.json).
  return { code: __httpCode, body: __httpResponse, data: __completionData };
}

function projectTasksList(description, expand, filter, filterIncludeNulls, filterTimezone, format, hexColor, id, identifier, isArchived, isFavorite, orderBy, owner, page, parentProjectId, perPage, position, project, q, sortBy, subscription, title) {
  var __url = "/projects/" + project + "/tasks";
  var __description = "List tasks in a project " + id;
  bp.log.info(__description);
  var __params = {};
  if (typeof page !== "undefined" && page !== null) { __params["page"] = (typeof page === "object" ? JSON.stringify(page) : page); }
  if (typeof perPage !== "undefined" && perPage !== null) { __params["per_page"] = (typeof perPage === "object" ? JSON.stringify(perPage) : perPage); }
  if (typeof q !== "undefined" && q !== null) { __params["q"] = (typeof q === "object" ? JSON.stringify(q) : q); }
  if (typeof filter !== "undefined" && filter !== null) { __params["filter"] = (typeof filter === "object" ? JSON.stringify(filter) : filter); }
  if (typeof filterTimezone !== "undefined" && filterTimezone !== null) { __params["filter_timezone"] = (typeof filterTimezone === "object" ? JSON.stringify(filterTimezone) : filterTimezone); }
  if (typeof filterIncludeNulls !== "undefined" && filterIncludeNulls !== null) { __params["filter_include_nulls"] = (typeof filterIncludeNulls === "object" ? JSON.stringify(filterIncludeNulls) : filterIncludeNulls); }
  if (typeof sortBy !== "undefined" && sortBy !== null) { __params["sort_by"] = (typeof sortBy === "object" ? JSON.stringify(sortBy) : sortBy); }
  if (typeof orderBy !== "undefined" && orderBy !== null) { __params["order_by"] = (typeof orderBy === "object" ? JSON.stringify(orderBy) : orderBy); }
  if (typeof expand !== "undefined" && expand !== null) { __params["expand"] = (typeof expand === "object" ? JSON.stringify(expand) : expand); }
  if (typeof format !== "undefined" && format !== null) { __params["format"] = (typeof format === "object" ? JSON.stringify(format) : format); }
  var __httpCode = null;
  var __httpResponse = null;
  svc.get(__url, { parameters: __params, expectedResponseCodes: [200], callback: function(response) {
    __httpCode = response.code;
    var __parsed = null;
    try { __parsed = JSON.parse(response.body); } catch (e) { /* non-JSON response body */ }
    __httpResponse = (__parsed !== null) ? __parsed : response.body;
  } });
  // NOTE: OpenAPI declares a 'default' response for this operation;
  // it is not mapped to a specific expectedResponseCodes entry (see generation_report.json).
  return { code: __httpCode, body: __httpResponse };
}

function tasksCreate(bucketId, coverImageAttachmentId, createdBy, description, done, dueDate, endDate, expand, format, hexColor, id, identifier, isArchived, isFavorite, owner, page, parentProjectId, perPage, percentDone, position, priority, project, projectId, q, reminders, repeatAfter, repeatMode, startDate, subscription, title) {
  var __url = "/projects/" + project + "/tasks";
  var __description = "Create a task " + id;
  bp.log.info(__description);
  var __params = {};
  if (typeof format !== "undefined" && format !== null) { __params["format"] = (typeof format === "object" ? JSON.stringify(format) : format); }
  var __body = {
    "bucket_id": bucketId,
    "cover_image_attachment_id": coverImageAttachmentId,
    "created_by": createdBy,
    "description": String(description),
    "done": done,
    "due_date": String(dueDate),
    "end_date": String(endDate),
    "hex_color": String(hexColor),
    "is_favorite": isFavorite,
    "percent_done": percentDone,
    "priority": priority,
    "project_id": projectId,
    "reminders": reminders,
    "repeat_after": repeatAfter,
    "repeat_mode": repeatMode,
    "start_date": String(startDate),
    "subscription": subscription,
    "title": String(title),
};
  var __httpCode = null;
  var __httpResponse = null;
  svc.post(__url, { body: JSON.stringify(__body), parameters: __params, expectedResponseCodes: [201], callback: function(response) {
    __httpCode = response.code;
    var __parsed = null;
    try { __parsed = JSON.parse(response.body); } catch (e) { /* non-JSON response body */ }
    __httpResponse = (__parsed !== null) ? __parsed : response.body;
  } });
  var __completionData = {"bucketId": bucketId, "coverImageAttachmentId": coverImageAttachmentId, "createdBy": createdBy, "description": description, "done": done, "dueDate": dueDate, "endDate": endDate, "expand": expand, "format": format, "hexColor": hexColor, "id": id, "identifier": identifier, "isArchived": isArchived, "isFavorite": isFavorite, "owner": owner, "page": page, "parentProjectId": parentProjectId, "perPage": perPage, "percentDone": percentDone, "position": position, "priority": priority, "project": project, "projectId": projectId, "q": q, "reminders": reminders, "repeatAfter": repeatAfter, "repeatMode": repeatMode, "startDate": startDate, "subscription": subscription, "title": title, "__httpCode": __httpCode, "__httpResponse": __httpResponse, "__entityKey": "projects"};
  sync({ request: Event("Done: " + __description, __completionData) });
  // NOTE: OpenAPI declares a 'default' response for this operation;
  // it is not mapped to a specific expectedResponseCodes entry (see generation_report.json).
  return { code: __httpCode, body: __httpResponse, data: __completionData };
}

// tryToAddExistingPaginatedProjects skipped: create operation documents no error response codes.

function verifyPaginatedProjectsExists(description, expand, format, hexColor, id, identifier, isArchived, isFavorite, owner, page, parentProjectId, perPage, position, q, subscription, title) {
  var __url = "/projects/" + id;
  svc.get(__url, { expectedResponseCodes: [200], callback: function(response) { pvg.success("PaginatedProjects found"); } });
}

// verifyPaginatedProjectsDoesNotExist skipped: GET /{id} does not document a 404 response.

function tryToDeleteANonExistingPaginatedProjects(description, expand, format, hexColor, id, identifier, isArchived, isFavorite, owner, page, parentProjectId, perPage, position, q, subscription, title) {
  var __url = "/projects/" + id;
  svc.delete(__url, { expectedResponseCodes: [204] });
}

function matchDeletedPaginatedProjects() {
  return EventSet("Delete PaginatedProjects", function(e) {
      return e.name.startsWith("Done: " + "Delete a project") && e.data && e.data["__entityKey"] === "projects";
  });
}

function waitForPaginatedProjectsAdded(description, expand, format, hexColor, id, identifier, isArchived, isFavorite, owner, page, parentProjectId, perPage, position, q, subscription, title) {
  waitFor(matchAnyPaginatedProjectsAdded());
}

function matchAnyPaginatedProjectsAdded() {
  return EventSet("Any PaginatedProjects Added", function(e) {
      return e.name.startsWith("Done: " + "Create a project") && e.data && e.data["__entityKey"] === "projects";
  });
}

function tasksDelete(ifMatch, ifModifiedSince, ifNoneMatch, ifUnmodifiedSince, bucketId, coverImageAttachmentId, createdBy, description, done, dueDate, endDate, expand, format, hexColor, isFavorite, percentDone, priority, projectId, reminders, repeatAfter, repeatMode, startDate, subscription, task, title) {
  var __url = "/tasks/" + task;
  var __description = "Delete a task " + task;
  bp.log.info(__description);
  var __httpCode = null;
  var __httpResponse = null;
  svc.delete(__url, { expectedResponseCodes: [204], callback: function(response) {
    __httpCode = response.code;
    var __parsed = null;
    try { __parsed = JSON.parse(response.body); } catch (e) { /* non-JSON response body */ }
    __httpResponse = (__parsed !== null) ? __parsed : response.body;
  } });
  var __completionData = {"ifMatch": ifMatch, "ifModifiedSince": ifModifiedSince, "ifNoneMatch": ifNoneMatch, "ifUnmodifiedSince": ifUnmodifiedSince, "bucketId": bucketId, "coverImageAttachmentId": coverImageAttachmentId, "createdBy": createdBy, "description": description, "done": done, "dueDate": dueDate, "endDate": endDate, "expand": expand, "format": format, "hexColor": hexColor, "isFavorite": isFavorite, "percentDone": percentDone, "priority": priority, "projectId": projectId, "reminders": reminders, "repeatAfter": repeatAfter, "repeatMode": repeatMode, "startDate": startDate, "subscription": subscription, "task": task, "title": title, "__httpCode": __httpCode, "__httpResponse": __httpResponse, "__entityKey": "tasks"};
  sync({ request: Event("Done: " + __description, __completionData) });
  // NOTE: OpenAPI declares a 'default' response for this operation;
  // it is not mapped to a specific expectedResponseCodes entry (see generation_report.json).
  return { code: __httpCode, body: __httpResponse, data: __completionData };
}

function tasksRead(ifMatch, ifModifiedSince, ifNoneMatch, ifUnmodifiedSince, bucketId, coverImageAttachmentId, createdBy, description, done, dueDate, endDate, expand, format, hexColor, isFavorite, percentDone, priority, projectId, reminders, repeatAfter, repeatMode, startDate, subscription, task, title) {
  var __url = "/tasks/" + task;
  var __description = "Get a task";
  bp.log.info(__description);
  var __params = {};
  if (typeof expand !== "undefined" && expand !== null) { __params["expand"] = (typeof expand === "object" ? JSON.stringify(expand) : expand); }
  if (typeof format !== "undefined" && format !== null) { __params["format"] = (typeof format === "object" ? JSON.stringify(format) : format); }
  var __headers = {};
  if (typeof ifMatch !== "undefined" && ifMatch !== null) { __headers["If-Match"] = String(ifMatch); }
  if (typeof ifNoneMatch !== "undefined" && ifNoneMatch !== null) { __headers["If-None-Match"] = String(ifNoneMatch); }
  if (typeof ifModifiedSince !== "undefined" && ifModifiedSince !== null) { __headers["If-Modified-Since"] = String(ifModifiedSince); }
  if (typeof ifUnmodifiedSince !== "undefined" && ifUnmodifiedSince !== null) { __headers["If-Unmodified-Since"] = String(ifUnmodifiedSince); }
  var __httpCode = null;
  var __httpResponse = null;
  svc.get(__url, { parameters: __params, headers: __headers, expectedResponseCodes: [200], callback: function(response) {
    __httpCode = response.code;
    var __parsed = null;
    try { __parsed = JSON.parse(response.body); } catch (e) { /* non-JSON response body */ }
    __httpResponse = (__parsed !== null) ? __parsed : response.body;
  } });
  // NOTE: OpenAPI declares a 'default' response for this operation;
  // it is not mapped to a specific expectedResponseCodes entry (see generation_report.json).
  return { code: __httpCode, body: __httpResponse };
}

function patchTasksRead(ifMatch, ifModifiedSince, ifNoneMatch, ifUnmodifiedSince, bucketId, coverImageAttachmentId, createdBy, description, done, dueDate, endDate, expand, format, hexColor, isFavorite, percentDone, priority, projectId, reminders, repeatAfter, repeatMode, startDate, subscription, task, title) {
  var __url = "/tasks/" + task;
  var __description = "Update a task (partial) " + task;
  bp.log.info(__description);
  var __body = undefined;
  var __httpCode = null;
  var __httpResponse = null;
  svc.patch(__url, { body: JSON.stringify(__body), expectedResponseCodes: [200], callback: function(response) {
    __httpCode = response.code;
    var __parsed = null;
    try { __parsed = JSON.parse(response.body); } catch (e) { /* non-JSON response body */ }
    __httpResponse = (__parsed !== null) ? __parsed : response.body;
  } });
  var __completionData = {"ifMatch": ifMatch, "ifModifiedSince": ifModifiedSince, "ifNoneMatch": ifNoneMatch, "ifUnmodifiedSince": ifUnmodifiedSince, "bucketId": bucketId, "coverImageAttachmentId": coverImageAttachmentId, "createdBy": createdBy, "description": description, "done": done, "dueDate": dueDate, "endDate": endDate, "expand": expand, "format": format, "hexColor": hexColor, "isFavorite": isFavorite, "percentDone": percentDone, "priority": priority, "projectId": projectId, "reminders": reminders, "repeatAfter": repeatAfter, "repeatMode": repeatMode, "startDate": startDate, "subscription": subscription, "task": task, "title": title, "__httpCode": __httpCode, "__httpResponse": __httpResponse, "__entityKey": "tasks"};
  sync({ request: Event("Done: " + __description, __completionData) });
  // NOTE: OpenAPI declares a 'default' response for this operation;
  // it is not mapped to a specific expectedResponseCodes entry (see generation_report.json).
  return { code: __httpCode, body: __httpResponse, data: __completionData };
}

function tasksUpdate(ifMatch, ifModifiedSince, ifNoneMatch, ifUnmodifiedSince, bucketId, coverImageAttachmentId, createdBy, description, done, dueDate, endDate, expand, format, hexColor, isFavorite, percentDone, priority, projectId, reminders, repeatAfter, repeatMode, startDate, subscription, task, title) {
  var __url = "/tasks/" + task;
  var __description = "Update a task " + task;
  bp.log.info(__description);
  var __params = {};
  if (typeof format !== "undefined" && format !== null) { __params["format"] = (typeof format === "object" ? JSON.stringify(format) : format); }
  var __body = {
    "bucket_id": bucketId,
    "cover_image_attachment_id": coverImageAttachmentId,
    "created_by": createdBy,
    "description": String(description),
    "done": done,
    "due_date": String(dueDate),
    "end_date": String(endDate),
    "hex_color": String(hexColor),
    "is_favorite": isFavorite,
    "percent_done": percentDone,
    "priority": priority,
    "project_id": projectId,
    "reminders": reminders,
    "repeat_after": repeatAfter,
    "repeat_mode": repeatMode,
    "start_date": String(startDate),
    "subscription": subscription,
    "title": String(title),
};
  var __httpCode = null;
  var __httpResponse = null;
  svc.put(__url, { body: JSON.stringify(__body), parameters: __params, expectedResponseCodes: [200], callback: function(response) {
    __httpCode = response.code;
    var __parsed = null;
    try { __parsed = JSON.parse(response.body); } catch (e) { /* non-JSON response body */ }
    __httpResponse = (__parsed !== null) ? __parsed : response.body;
  } });
  var __completionData = {"ifMatch": ifMatch, "ifModifiedSince": ifModifiedSince, "ifNoneMatch": ifNoneMatch, "ifUnmodifiedSince": ifUnmodifiedSince, "bucketId": bucketId, "coverImageAttachmentId": coverImageAttachmentId, "createdBy": createdBy, "description": description, "done": done, "dueDate": dueDate, "endDate": endDate, "expand": expand, "format": format, "hexColor": hexColor, "isFavorite": isFavorite, "percentDone": percentDone, "priority": priority, "projectId": projectId, "reminders": reminders, "repeatAfter": repeatAfter, "repeatMode": repeatMode, "startDate": startDate, "subscription": subscription, "task": task, "title": title, "__httpCode": __httpCode, "__httpResponse": __httpResponse, "__entityKey": "tasks"};
  sync({ request: Event("Done: " + __description, __completionData) });
  // NOTE: OpenAPI declares a 'default' response for this operation;
  // it is not mapped to a specific expectedResponseCodes entry (see generation_report.json).
  return { code: __httpCode, body: __httpResponse, data: __completionData };
}

function taskLabelsList(ifMatch, ifModifiedSince, ifNoneMatch, ifUnmodifiedSince, bucketId, coverImageAttachmentId, createdBy, description, done, dueDate, endDate, expand, format, hexColor, isFavorite, page, perPage, percentDone, priority, projectId, q, reminders, repeatAfter, repeatMode, startDate, subscription, task, title) {
  var __url = "/tasks/" + task + "/labels";
  var __description = "List the labels on a task " + task;
  bp.log.info(__description);
  var __params = {};
  if (typeof page !== "undefined" && page !== null) { __params["page"] = (typeof page === "object" ? JSON.stringify(page) : page); }
  if (typeof perPage !== "undefined" && perPage !== null) { __params["per_page"] = (typeof perPage === "object" ? JSON.stringify(perPage) : perPage); }
  if (typeof q !== "undefined" && q !== null) { __params["q"] = (typeof q === "object" ? JSON.stringify(q) : q); }
  var __httpCode = null;
  var __httpResponse = null;
  svc.get(__url, { parameters: __params, expectedResponseCodes: [200], callback: function(response) {
    __httpCode = response.code;
    var __parsed = null;
    try { __parsed = JSON.parse(response.body); } catch (e) { /* non-JSON response body */ }
    __httpResponse = (__parsed !== null) ? __parsed : response.body;
  } });
  // NOTE: OpenAPI declares a 'default' response for this operation;
  // it is not mapped to a specific expectedResponseCodes entry (see generation_report.json).
  return { code: __httpCode, body: __httpResponse };
}

function taskLabelsCreate(ifMatch, ifModifiedSince, ifNoneMatch, ifUnmodifiedSince, bucketId, coverImageAttachmentId, createdBy, description, done, dueDate, endDate, expand, format, hexColor, isFavorite, labelId, percentDone, priority, projectId, reminders, repeatAfter, repeatMode, startDate, subscription, task, title) {
  var __url = "/tasks/" + task + "/labels";
  var __description = "Add a label to a task " + task;
  bp.log.info(__description);
  var __body = {
    "label_id": labelId,
};
  var __httpCode = null;
  var __httpResponse = null;
  svc.post(__url, { body: JSON.stringify(__body), expectedResponseCodes: [201], callback: function(response) {
    __httpCode = response.code;
    var __parsed = null;
    try { __parsed = JSON.parse(response.body); } catch (e) { /* non-JSON response body */ }
    __httpResponse = (__parsed !== null) ? __parsed : response.body;
  } });
  var __completionData = {"ifMatch": ifMatch, "ifModifiedSince": ifModifiedSince, "ifNoneMatch": ifNoneMatch, "ifUnmodifiedSince": ifUnmodifiedSince, "bucketId": bucketId, "coverImageAttachmentId": coverImageAttachmentId, "createdBy": createdBy, "description": description, "done": done, "dueDate": dueDate, "endDate": endDate, "expand": expand, "format": format, "hexColor": hexColor, "isFavorite": isFavorite, "labelId": labelId, "percentDone": percentDone, "priority": priority, "projectId": projectId, "reminders": reminders, "repeatAfter": repeatAfter, "repeatMode": repeatMode, "startDate": startDate, "subscription": subscription, "task": task, "title": title, "__httpCode": __httpCode, "__httpResponse": __httpResponse, "__entityKey": "tasks"};
  sync({ request: Event("Done: " + __description, __completionData) });
  // NOTE: OpenAPI declares a 'default' response for this operation;
  // it is not mapped to a specific expectedResponseCodes entry (see generation_report.json).
  return { code: __httpCode, body: __httpResponse, data: __completionData };
}

function taskLabelsDelete(ifMatch, ifModifiedSince, ifNoneMatch, ifUnmodifiedSince, bucketId, coverImageAttachmentId, createdBy, description, done, dueDate, endDate, expand, format, hexColor, isFavorite, label, percentDone, priority, projectId, reminders, repeatAfter, repeatMode, startDate, subscription, task, title) {
  var __url = "/tasks/" + task + "/labels/" + label;
  var __description = "Remove a label from a task " + label;
  bp.log.info(__description);
  var __httpCode = null;
  var __httpResponse = null;
  svc.delete(__url, { expectedResponseCodes: [204], callback: function(response) {
    __httpCode = response.code;
    var __parsed = null;
    try { __parsed = JSON.parse(response.body); } catch (e) { /* non-JSON response body */ }
    __httpResponse = (__parsed !== null) ? __parsed : response.body;
  } });
  var __completionData = {"ifMatch": ifMatch, "ifModifiedSince": ifModifiedSince, "ifNoneMatch": ifNoneMatch, "ifUnmodifiedSince": ifUnmodifiedSince, "bucketId": bucketId, "coverImageAttachmentId": coverImageAttachmentId, "createdBy": createdBy, "description": description, "done": done, "dueDate": dueDate, "endDate": endDate, "expand": expand, "format": format, "hexColor": hexColor, "isFavorite": isFavorite, "label": label, "percentDone": percentDone, "priority": priority, "projectId": projectId, "reminders": reminders, "repeatAfter": repeatAfter, "repeatMode": repeatMode, "startDate": startDate, "subscription": subscription, "task": task, "title": title, "__httpCode": __httpCode, "__httpResponse": __httpResponse, "__entityKey": "tasks"};
  sync({ request: Event("Done: " + __description, __completionData) });
  // NOTE: OpenAPI declares a 'default' response for this operation;
  // it is not mapped to a specific expectedResponseCodes entry (see generation_report.json).
  return { code: __httpCode, body: __httpResponse, data: __completionData };
}

function verifyTaskReadOneBodiesExists(ifMatch, ifModifiedSince, ifNoneMatch, ifUnmodifiedSince, bucketId, coverImageAttachmentId, createdBy, description, done, dueDate, endDate, expand, format, hexColor, isFavorite, percentDone, priority, projectId, reminders, repeatAfter, repeatMode, startDate, subscription, task, title) {
  var __url = "/tasks/" + task;
  svc.get(__url, { expectedResponseCodes: [200], callback: function(response) { pvg.success("TaskReadOneBodies found"); } });
}

// verifyTaskReadOneBodiesDoesNotExist skipped: GET /{id} does not document a 404 response.

function tryToDeleteANonExistingTaskReadOneBodies(ifMatch, ifModifiedSince, ifNoneMatch, ifUnmodifiedSince, bucketId, coverImageAttachmentId, createdBy, description, done, dueDate, endDate, expand, format, hexColor, isFavorite, percentDone, priority, projectId, reminders, repeatAfter, repeatMode, startDate, subscription, task, title) {
  var __url = "/tasks/" + task;
  svc.delete(__url, { expectedResponseCodes: [204] });
}

function matchDeletedTaskReadOneBodies() {
  return EventSet("Delete TaskReadOneBodies", function(e) {
      return e.name.startsWith("Done: " + "Delete a task") && e.data && e.data["__entityKey"] === "tasks";
  });
}
