// Auto-generated stories for vikunja
// Generated by openapi_to_sbt. Do not edit by hand; regenerate instead.
//@provengo summon rest

function resolveDependencies(deps, pkMap) {
  let captured = {};
  while (Object.keys(deps).length > 0) {
    let missingEventSets = Object.values(deps);
    let e = sync({waitFor: missingEventSets});
    for (let k in deps) {
      if (deps[k].contains(e)) {
        let val = (e.data && e.data[k]);
        if (!val && pkMap && pkMap[k]) {
            let mappedKey = pkMap[k];
            val = (e.data && e.data[mappedKey]);
        }
        if (!val && e.data) {
          for (let f in e.data) { if (f.toLowerCase().indexOf("id") > -1) { val = e.data[f]; break; } }
        }
        if (val !== undefined) {
            captured[k] = val;
            delete deps[k];
        }
      }
    }
  }
  return captured;
}


// ==============================================================================
// STATE TRACKER (contract-derived: tracks identifiers returned by create operations)
// ==============================================================================
const STATE = { paginatedLabelWithTaskIDs: [], paginatedProjects: [] };

bthread("monitor:StateTracker", function() {
    while (true) {
        let e = sync({ waitFor: [matchAnyPaginatedLabelWithTaskIDsAdded(), matchAnyPaginatedProjectsAdded()] });
        if (e.data && e.data["__entityKey"] === "labels") {
            STATE.paginatedLabelWithTaskIDs.push(e.data.id);
        }
        else if (e.data && e.data["__entityKey"] === "projects") {
            STATE.paginatedProjects.push(e.data.id);
        }
    }
});

bthread("crud:PaginatedLabelWithTaskIDs:1", function() {
  let ifMatch = "1_96517";
  let ifModifiedSince = "1_87105";
  let ifNoneMatch = "1_9339";
  let ifUnmodifiedSince = "1_20244";
  let createdBy = {"name": "name_11730", "username": "username_20622"};
  let description = "1_39976";
  let format = "markdown";
  let hexColor = "1_32696";
  let id = 10084;
  let page = "1_56282";
  let perPage = "1_78222";
  let q = "1_20326";
  let title = "1_59320";
  let __createResult = labelsCreate(ifMatch, ifModifiedSince, ifNoneMatch, ifUnmodifiedSince, createdBy, description, format, hexColor, id, page, perPage, q, title);
  let __justCreated = (__createResult && __createResult.data) ? __createResult.data : {};
  sync({ request: Event("InstanceReady:PaginatedLabelWithTaskIDs:1", { ifMatch: __justCreated["ifMatch"], ifModifiedSince: __justCreated["ifModifiedSince"], ifNoneMatch: __justCreated["ifNoneMatch"], ifUnmodifiedSince: __justCreated["ifUnmodifiedSince"], createdBy: __justCreated["createdBy"], description: __justCreated["description"], format: __justCreated["format"], hexColor: __justCreated["hexColor"], id: __justCreated["id"], page: __justCreated["page"], perPage: __justCreated["perPage"], q: __justCreated["q"], title: __justCreated["title"] }) });
  sync({ request: Event("StoryPhaseComplete:crud:PaginatedLabelWithTaskIDs:1") });
});

bthread("crud:PaginatedProjects:1", function() {
  let description = "1_15407";
  let expand = "1_48365";
  let format = "html";
  let hexColor = "1_73518";
  let id = 23542;
  let identifier = "1_96417";
  let isArchived = false;
  let isFavorite = true;
  let owner = {"email": "email_47690"};
  let page = "1_51941";
  let parentProjectId = 85647;
  let perPage = "1_92858";
  let position = 518.0;
  let q = "1_75141";
  let subscription = {};
  let title = "1_80426";
  let __createResult = projectsCreate(description, expand, format, hexColor, id, identifier, isArchived, isFavorite, owner, page, parentProjectId, perPage, position, q, subscription, title);
  let __justCreated = (__createResult && __createResult.data) ? __createResult.data : {};
  sync({ request: Event("InstanceReady:PaginatedProjects:1", { description: __justCreated["description"], expand: __justCreated["expand"], format: __justCreated["format"], hexColor: __justCreated["hexColor"], id: __justCreated["id"], identifier: __justCreated["identifier"], isArchived: __justCreated["isArchived"], isFavorite: __justCreated["isFavorite"], owner: __justCreated["owner"], page: __justCreated["page"], parentProjectId: __justCreated["parentProjectId"], perPage: __justCreated["perPage"], position: __justCreated["position"], q: __justCreated["q"], subscription: __justCreated["subscription"], title: __justCreated["title"] }) });
  sync({ request: Event("StoryPhaseComplete:crud:PaginatedProjects:1") });
});

// ==============================================================================
// ACTION / STANDALONE OPERATION STORIES: exercises every non-CRUD operation
// (entity sub-actions and fully standalone operations) at least once, wiring in
// real values captured from already-created entities where the operation's own
// parameters match one (DEVELOPMENT_PROMPT.md #10).
// ==============================================================================

bthread("update:patchLabelsRead:1", function() {
  let deps = {};
  let pkMap = {};
  deps["id"] = EventSet("wait:InstanceReady:PaginatedLabelWithTaskIDs:1", function(e) { return e.name === "InstanceReady:PaginatedLabelWithTaskIDs:1"; });
  pkMap["id"] = "id";
  let captured = resolveDependencies(deps, pkMap);
  let ifMatch = "1_77196";
  let ifModifiedSince = "1_88590";
  let ifNoneMatch = "1_26821";
  let ifUnmodifiedSince = "1_77679";
  let createdBy = "1_62890";
  let description = "1_86341";
  let format = "1_40276";
  let hexColor = "1_84031";
  let id = captured["id"];
  let page = "1_79464";
  let perPage = "1_421";
  let q = "1_25042";
  let title = "1_5662";
  patchLabelsRead(ifMatch, ifModifiedSince, ifNoneMatch, ifUnmodifiedSince, createdBy, description, format, hexColor, id, page, perPage, q, title);
  sync({ request: Event("StoryPhaseComplete:update:patchLabelsRead:1") });
});

bthread("update:labelsUpdate:1", function() {
  let deps = {};
  let pkMap = {};
  deps["id"] = EventSet("wait:InstanceReady:PaginatedLabelWithTaskIDs:1", function(e) { return e.name === "InstanceReady:PaginatedLabelWithTaskIDs:1"; });
  pkMap["id"] = "id";
  let captured = resolveDependencies(deps, pkMap);
  let ifMatch = "1_28034";
  let ifModifiedSince = "1_14159";
  let ifNoneMatch = "1_60175";
  let ifUnmodifiedSince = "1_59420";
  let createdBy = {"name": "name_81062", "username": "username_16952"};
  let description = "1_18";
  let format = "markdown";
  let hexColor = "1_43547";
  let id = captured["id"];
  let page = "1_18782";
  let perPage = "1_71528";
  let q = "1_42166";
  let title = "1_32393";
  labelsUpdate(ifMatch, ifModifiedSince, ifNoneMatch, ifUnmodifiedSince, createdBy, description, format, hexColor, id, page, perPage, q, title);
  sync({ request: Event("StoryPhaseComplete:update:labelsUpdate:1") });
});

bthread("update:patchProjectsRead:1", function() {
  let deps = {};
  let pkMap = {};
  deps["id"] = EventSet("wait:InstanceReady:PaginatedProjects:1", function(e) { return e.name === "InstanceReady:PaginatedProjects:1"; });
  pkMap["id"] = "id";
  let captured = resolveDependencies(deps, pkMap);
  let description = "1_18055";
  let expand = "1_60736";
  let format = "1_90795";
  let hexColor = "1_74659";
  let id = captured["id"];
  let identifier = "1_18700";
  let isArchived = false;
  let isFavorite = false;
  let owner = "1_56880";
  let page = "1_34934";
  let parentProjectId = 15835;
  let perPage = "1_2414";
  let position = 601.0;
  let q = "1_49430";
  let subscription = "1_45951";
  let title = "1_56849";
  patchProjectsRead(description, expand, format, hexColor, id, identifier, isArchived, isFavorite, owner, page, parentProjectId, perPage, position, q, subscription, title);
  sync({ request: Event("StoryPhaseComplete:update:patchProjectsRead:1") });
});

bthread("update:projectsUpdate:1", function() {
  let deps = {};
  let pkMap = {};
  deps["id"] = EventSet("wait:InstanceReady:PaginatedProjects:1", function(e) { return e.name === "InstanceReady:PaginatedProjects:1"; });
  pkMap["id"] = "id";
  let captured = resolveDependencies(deps, pkMap);
  let description = "1_63006";
  let expand = "1_92112";
  let format = "html";
  let hexColor = "1_62519";
  let id = captured["id"];
  let identifier = "1_64424";
  let isArchived = false;
  let isFavorite = true;
  let owner = {"email": "email_59256", "username": "username_52902"};
  let page = "1_77744";
  let parentProjectId = 98600;
  let perPage = "1_55988";
  let position = 952.0;
  let q = "1_26436";
  let subscription = {};
  let title = "1_58810";
  projectsUpdate(description, expand, format, hexColor, id, identifier, isArchived, isFavorite, owner, page, parentProjectId, perPage, position, q, subscription, title);
  sync({ request: Event("StoryPhaseComplete:update:projectsUpdate:1") });
});

bthread("action:projectTasksList:1", function() {
  let deps = {};
  let pkMap = {};
  deps["project"] = EventSet("wait:InstanceReady:PaginatedProjects:1", function(e) { return e.name === "InstanceReady:PaginatedProjects:1"; });
  pkMap["project"] = "id";
  let captured = resolveDependencies(deps, pkMap);
  let description = "1_25791";
  let expand = ["subtasks"];
  let filter = "1_43161";
  let filterIncludeNulls = true;
  let filterTimezone = "1_46332";
  let format = "html";
  let hexColor = "1_24109";
  let id = "1_66636";
  let identifier = "1_1058";
  let isArchived = "1_34781";
  let isFavorite = "1_75524";
  let orderBy = ["1_58093"];
  let owner = "1_18026";
  let page = 1;
  let parentProjectId = "1_46932";
  let perPage = 50;
  let position = "1_22585";
  let project = captured["project"];
  let q = "1_88488";
  let sortBy = ["1_97372"];
  let subscription = "1_96826";
  let title = "1_80645";
  projectTasksList(description, expand, filter, filterIncludeNulls, filterTimezone, format, hexColor, id, identifier, isArchived, isFavorite, orderBy, owner, page, parentProjectId, perPage, position, project, q, sortBy, subscription, title);
  sync({ request: Event("StoryPhaseComplete:action:projectTasksList:1") });
});

bthread("action:tasksCreate:1", function() {
  let deps = {};
  let pkMap = {};
  deps["project"] = EventSet("wait:InstanceReady:PaginatedProjects:1", function(e) { return e.name === "InstanceReady:PaginatedProjects:1"; });
  pkMap["project"] = "id";
  let captured = resolveDependencies(deps, pkMap);
  let bucketId = 79604;
  let coverImageAttachmentId = 4542;
  let createdBy = {"name": "name_47648", "username": "username_42288"};
  let description = "1_88329";
  let done = true;
  let dueDate = "2025-01-22T00:00:00Z";
  let endDate = "2025-01-20T00:00:00Z";
  let expand = "1_59804";
  let format = "markdown";
  let hexColor = "1_95103";
  let id = 11540;
  let identifier = "1_64215";
  let isArchived = "1_81448";
  let isFavorite = false;
  let owner = "1_76027";
  let page = "1_93666";
  let parentProjectId = "1_13031";
  let perPage = "1_2168";
  let percentDone = 48.0;
  let position = 990.0;
  let priority = 92670;
  let project = captured["project"];
  let projectId = 75246;
  let q = "1_53725";
  let reminders = [{"relative_period": 42972, "reminder": "2025-01-09T00:00:00Z"}];
  let repeatAfter = 74132;
  let repeatMode = 7709;
  let startDate = "2025-01-23T00:00:00Z";
  let subscription = {};
  let title = "1_34630";
  tasksCreate(bucketId, coverImageAttachmentId, createdBy, description, done, dueDate, endDate, expand, format, hexColor, id, identifier, isArchived, isFavorite, owner, page, parentProjectId, perPage, percentDone, position, priority, project, projectId, q, reminders, repeatAfter, repeatMode, startDate, subscription, title);
  sync({ request: Event("StoryPhaseComplete:action:tasksCreate:1") });
});

bthread("update:patchTasksRead:1", function() {
  let ifMatch = "1_28409";
  let ifModifiedSince = "1_62626";
  let ifNoneMatch = "1_42186";
  let ifUnmodifiedSince = "1_23166";
  let bucketId = 11291;
  let coverImageAttachmentId = 83786;
  let createdBy = "1_13395";
  let description = "1_61881";
  let done = true;
  let dueDate = "2025-01-20T00:00:00Z";
  let endDate = "2025-01-19T00:00:00Z";
  let expand = "1_6812";
  let format = "1_24152";
  let hexColor = "1_11665";
  let isFavorite = false;
  let percentDone = 92.0;
  let priority = 84614;
  let projectId = 98794;
  let reminders = ["1_89385"];
  let repeatAfter = 21935;
  let repeatMode = 48573;
  let startDate = "2025-01-09T00:00:00Z";
  let subscription = "1_24606";
  let task = "1_12408";
  let title = "1_28995";
  patchTasksRead(ifMatch, ifModifiedSince, ifNoneMatch, ifUnmodifiedSince, bucketId, coverImageAttachmentId, createdBy, description, done, dueDate, endDate, expand, format, hexColor, isFavorite, percentDone, priority, projectId, reminders, repeatAfter, repeatMode, startDate, subscription, task, title);
  sync({ request: Event("StoryPhaseComplete:update:patchTasksRead:1") });
});

bthread("update:tasksUpdate:1", function() {
  let deps = {};
  let pkMap = {};
  deps["projectId"] = EventSet("wait:InstanceReady:PaginatedProjects:1", function(e) { return e.name === "InstanceReady:PaginatedProjects:1"; });
  pkMap["projectId"] = "id";
  let captured = resolveDependencies(deps, pkMap);
  let ifMatch = "1_35655";
  let ifModifiedSince = "1_31829";
  let ifNoneMatch = "1_64318";
  let ifUnmodifiedSince = "1_99204";
  let bucketId = 56107;
  let coverImageAttachmentId = 43834;
  let createdBy = {"email": "email_11474", "name": "name_6138", "username": "username_85532"};
  let description = "1_69350";
  let done = false;
  let dueDate = "2025-01-15T00:00:00Z";
  let endDate = "2025-01-09T00:00:00Z";
  let expand = "1_53967";
  let format = "markdown";
  let hexColor = "1_71206";
  let isFavorite = false;
  let percentDone = 952.0;
  let priority = 75598;
  let projectId = captured["projectId"];
  let reminders = [{"relative_period": 15691, "reminder": "2025-01-25T00:00:00Z"}];
  let repeatAfter = 2002;
  let repeatMode = 80152;
  let startDate = "2025-01-21T00:00:00Z";
  let subscription = {};
  let task = "1_99202";
  let title = "1_14255";
  tasksUpdate(ifMatch, ifModifiedSince, ifNoneMatch, ifUnmodifiedSince, bucketId, coverImageAttachmentId, createdBy, description, done, dueDate, endDate, expand, format, hexColor, isFavorite, percentDone, priority, projectId, reminders, repeatAfter, repeatMode, startDate, subscription, task, title);
  sync({ request: Event("StoryPhaseComplete:update:tasksUpdate:1") });
});

bthread("standalone:taskLabelsList:1", function() {
  let ifMatch = "1_24569";
  let ifModifiedSince = "1_72140";
  let ifNoneMatch = "1_88149";
  let ifUnmodifiedSince = "1_25165";
  let bucketId = "1_1853";
  let coverImageAttachmentId = "1_81051";
  let createdBy = "1_43659";
  let description = "1_78492";
  let done = "1_56540";
  let dueDate = "1_10254";
  let endDate = "1_55509";
  let expand = "1_22860";
  let format = "1_64731";
  let hexColor = "1_1002";
  let isFavorite = "1_46543";
  let page = 1;
  let perPage = 50;
  let percentDone = "1_54187";
  let priority = "1_55224";
  let projectId = "1_5993";
  let q = "1_9854";
  let reminders = "1_46656";
  let repeatAfter = "1_7414";
  let repeatMode = "1_11158";
  let startDate = "1_66326";
  let subscription = "1_57686";
  let task = "1_17177";
  let title = "1_22425";
  taskLabelsList(ifMatch, ifModifiedSince, ifNoneMatch, ifUnmodifiedSince, bucketId, coverImageAttachmentId, createdBy, description, done, dueDate, endDate, expand, format, hexColor, isFavorite, page, perPage, percentDone, priority, projectId, q, reminders, repeatAfter, repeatMode, startDate, subscription, task, title);
  sync({ request: Event("StoryPhaseComplete:standalone:taskLabelsList:1") });
});

bthread("standalone:taskLabelsCreate:1", function() {
  let deps = {};
  let pkMap = {};
  deps["labelId"] = EventSet("wait:InstanceReady:PaginatedLabelWithTaskIDs:1", function(e) { return e.name === "InstanceReady:PaginatedLabelWithTaskIDs:1"; });
  pkMap["labelId"] = "id";
  let captured = resolveDependencies(deps, pkMap);
  let ifMatch = "1_82554";
  let ifModifiedSince = "1_36046";
  let ifNoneMatch = "1_26703";
  let ifUnmodifiedSince = "1_40555";
  let bucketId = "1_81301";
  let coverImageAttachmentId = "1_26654";
  let createdBy = "1_25512";
  let description = "1_2207";
  let done = "1_14146";
  let dueDate = "1_6386";
  let endDate = "1_88912";
  let expand = "1_31";
  let format = "1_70007";
  let hexColor = "1_80513";
  let isFavorite = "1_42055";
  let labelId = captured["labelId"];
  let percentDone = "1_90";
  let priority = "1_53353";
  let projectId = "1_42184";
  let reminders = "1_64627";
  let repeatAfter = "1_91082";
  let repeatMode = "1_37620";
  let startDate = "1_69929";
  let subscription = "1_88410";
  let task = "1_17703";
  let title = "1_85564";
  taskLabelsCreate(ifMatch, ifModifiedSince, ifNoneMatch, ifUnmodifiedSince, bucketId, coverImageAttachmentId, createdBy, description, done, dueDate, endDate, expand, format, hexColor, isFavorite, labelId, percentDone, priority, projectId, reminders, repeatAfter, repeatMode, startDate, subscription, task, title);
  sync({ request: Event("StoryPhaseComplete:standalone:taskLabelsCreate:1") });
});

bthread("standalone:taskLabelsDelete:1", function() {
  let ifMatch = "1_62529";
  let ifModifiedSince = "1_78747";
  let ifNoneMatch = "1_38086";
  let ifUnmodifiedSince = "1_47380";
  let bucketId = "1_72602";
  let coverImageAttachmentId = "1_78254";
  let createdBy = "1_46465";
  let description = "1_70273";
  let done = "1_25674";
  let dueDate = "1_36954";
  let endDate = "1_62153";
  let expand = "1_34527";
  let format = "1_43279";
  let hexColor = "1_67112";
  let isFavorite = "1_26311";
  let label = "1_40554";
  let percentDone = "1_71560";
  let priority = "1_59761";
  let projectId = "1_1460";
  let reminders = "1_77596";
  let repeatAfter = "1_56546";
  let repeatMode = "1_57426";
  let startDate = "1_52156";
  let subscription = "1_49044";
  let task = "1_27894";
  let title = "1_1629";
  taskLabelsDelete(ifMatch, ifModifiedSince, ifNoneMatch, ifUnmodifiedSince, bucketId, coverImageAttachmentId, createdBy, description, done, dueDate, endDate, expand, format, hexColor, isFavorite, label, percentDone, priority, projectId, reminders, repeatAfter, repeatMode, startDate, subscription, task, title);
  sync({ request: Event("StoryPhaseComplete:standalone:taskLabelsDelete:1") });
});

// ==============================================================================
// LIFECYCLE CLEANUP: deletes created instances in reverse dependency order
// (dependents before parents), per required lifecycle ordering.
// ==============================================================================
bthread("lifecycle:ReverseDeletion", function() {
    let __pendingStories = {};
    __pendingStories["StoryPhaseComplete:crud:PaginatedLabelWithTaskIDs:1"] = EventSet("Wait StoryPhaseComplete:crud:PaginatedLabelWithTaskIDs:1", function(e) { return e.name === "StoryPhaseComplete:crud:PaginatedLabelWithTaskIDs:1"; });
    __pendingStories["StoryPhaseComplete:crud:PaginatedProjects:1"] = EventSet("Wait StoryPhaseComplete:crud:PaginatedProjects:1", function(e) { return e.name === "StoryPhaseComplete:crud:PaginatedProjects:1"; });
    __pendingStories["StoryPhaseComplete:update:patchLabelsRead:1"] = EventSet("Wait StoryPhaseComplete:update:patchLabelsRead:1", function(e) { return e.name === "StoryPhaseComplete:update:patchLabelsRead:1"; });
    __pendingStories["StoryPhaseComplete:update:labelsUpdate:1"] = EventSet("Wait StoryPhaseComplete:update:labelsUpdate:1", function(e) { return e.name === "StoryPhaseComplete:update:labelsUpdate:1"; });
    __pendingStories["StoryPhaseComplete:update:patchProjectsRead:1"] = EventSet("Wait StoryPhaseComplete:update:patchProjectsRead:1", function(e) { return e.name === "StoryPhaseComplete:update:patchProjectsRead:1"; });
    __pendingStories["StoryPhaseComplete:update:projectsUpdate:1"] = EventSet("Wait StoryPhaseComplete:update:projectsUpdate:1", function(e) { return e.name === "StoryPhaseComplete:update:projectsUpdate:1"; });
    __pendingStories["StoryPhaseComplete:action:projectTasksList:1"] = EventSet("Wait StoryPhaseComplete:action:projectTasksList:1", function(e) { return e.name === "StoryPhaseComplete:action:projectTasksList:1"; });
    __pendingStories["StoryPhaseComplete:action:tasksCreate:1"] = EventSet("Wait StoryPhaseComplete:action:tasksCreate:1", function(e) { return e.name === "StoryPhaseComplete:action:tasksCreate:1"; });
    __pendingStories["StoryPhaseComplete:update:patchTasksRead:1"] = EventSet("Wait StoryPhaseComplete:update:patchTasksRead:1", function(e) { return e.name === "StoryPhaseComplete:update:patchTasksRead:1"; });
    __pendingStories["StoryPhaseComplete:update:tasksUpdate:1"] = EventSet("Wait StoryPhaseComplete:update:tasksUpdate:1", function(e) { return e.name === "StoryPhaseComplete:update:tasksUpdate:1"; });
    __pendingStories["StoryPhaseComplete:standalone:taskLabelsList:1"] = EventSet("Wait StoryPhaseComplete:standalone:taskLabelsList:1", function(e) { return e.name === "StoryPhaseComplete:standalone:taskLabelsList:1"; });
    __pendingStories["StoryPhaseComplete:standalone:taskLabelsCreate:1"] = EventSet("Wait StoryPhaseComplete:standalone:taskLabelsCreate:1", function(e) { return e.name === "StoryPhaseComplete:standalone:taskLabelsCreate:1"; });
    __pendingStories["StoryPhaseComplete:standalone:taskLabelsDelete:1"] = EventSet("Wait StoryPhaseComplete:standalone:taskLabelsDelete:1", function(e) { return e.name === "StoryPhaseComplete:standalone:taskLabelsDelete:1"; });
    while (Object.keys(__pendingStories).length > 0) {
        let __phaseEvent = sync({ waitFor: Object.values(__pendingStories) });
        for (let __storyName in __pendingStories) {
            if (__pendingStories[__storyName].contains(__phaseEvent)) {
                delete __pendingStories[__storyName];
                break;
            }
        }
    }
    for (let i = 0; i < STATE.paginatedProjects.length; i++) {
        let id = STATE.paginatedProjects[i];
        let description = undefined;
        let expand = undefined;
        let format = undefined;
        let hexColor = undefined;
        let identifier = undefined;
        let isArchived = undefined;
        let isFavorite = undefined;
        let owner = undefined;
        let page = undefined;
        let parentProjectId = undefined;
        let perPage = undefined;
        let position = undefined;
        let q = undefined;
        let subscription = undefined;
        let title = undefined;
        projectsDelete(description, expand, format, hexColor, id, identifier, isArchived, isFavorite, owner, page, parentProjectId, perPage, position, q, subscription, title);
    }
    for (let i = 0; i < STATE.paginatedLabelWithTaskIDs.length; i++) {
        let id = STATE.paginatedLabelWithTaskIDs[i];
        let ifMatch = undefined;
        let ifModifiedSince = undefined;
        let ifNoneMatch = undefined;
        let ifUnmodifiedSince = undefined;
        let createdBy = undefined;
        let description = undefined;
        let format = undefined;
        let hexColor = undefined;
        let page = undefined;
        let perPage = undefined;
        let q = undefined;
        let title = undefined;
        labelsDelete(ifMatch, ifModifiedSince, ifNoneMatch, ifUnmodifiedSince, createdBy, description, format, hexColor, id, page, perPage, q, title);
    }
});
