// Auto-generated stories for vikunja
// Generated by openapi_to_sbt. Do not edit by hand; regenerate instead.
//@provengo summon rest

function resolveDependencies(deps, pkMap) {
  let captured = {};
  while (Object.keys(deps).length > 0) {
    let missingEventSets = Object.values(deps);
    let e = sync({waitFor: missingEventSets});
    for (let k in deps) {
      if (deps[k].contains(e)) {
        let val = (e.data && e.data[k]);
        if (!val && pkMap && pkMap[k]) {
            let mappedKey = pkMap[k];
            val = (e.data && e.data[mappedKey]);
        }
        if (!val && e.data) {
          for (let f in e.data) { if (f.toLowerCase().indexOf("id") > -1) { val = e.data[f]; break; } }
        }
        if (val !== undefined) {
            captured[k] = val;
            delete deps[k];
        }
      }
    }
  }
  return captured;
}


bthread("validated-action-lifecycle:contract-derived", function() {
  let __parentCreate_title = "title_84449";
  let __parentCreate = projectsCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __parentCreate_title);
  let __parentId = __parentCreate.data["id"];
  projectsRead(undefined, undefined, undefined, undefined, __parentId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  let __childCreate_title = "title_68203";
  let __childCreate = tasksCreate(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __parentId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __childCreate_title);
  let __childId = __childCreate.data["task"];
  tasksRead(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __childId, undefined);
  let __initialValue = "create_3276";
  let __subresourceCreate = taskCommentsCreate(undefined, undefined, undefined, undefined, undefined, undefined, __initialValue, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __childId, undefined);
  let __subresourceId = (__subresourceCreate.data["id"] !== undefined ? __subresourceCreate.data["id"] : __subresourceCreate.data.__httpResponse["id"]);
  taskCommentsRead(undefined, undefined, undefined, undefined, undefined, __subresourceId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __childId, undefined);
  taskCommentsList(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __childId, undefined);
  let __updatedValue = "update_89133";
  taskCommentsUpdate(undefined, undefined, undefined, undefined, undefined, undefined, __updatedValue, __subresourceId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __childId, undefined);
  taskCommentsRead(undefined, undefined, undefined, undefined, undefined, __subresourceId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __childId, undefined);
  taskCommentsDelete(undefined, undefined, undefined, undefined, undefined, __subresourceId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __childId, undefined);
  taskCommentsList(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __childId, undefined);
  tasksDelete(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, __childId, undefined);
  projectsDelete(undefined, undefined, undefined, undefined, __parentId, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  sync({ request: Event("ValidatedActionLifecycleComplete") });
});
